<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>3&nbsp; Modelos de Elección Discreta – Manual de Microeconometría</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03-tobit.html" rel="next">
<link href="./01-vd-limitada.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./02-eleccion-discreta.html"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Modelos de Elección Discreta</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Manual de Microeconometría</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prólogo</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00-fundamentos.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Fundamentos de Probabilidad, Inferencia y Econometría</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-vd-limitada.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Datos con Variable Dependiente Limitada</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-eleccion-discreta.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Modelos de Elección Discreta</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-tobit.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelos para Datos Censurados (Tobit)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-recuento.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Modelos para Datos de Recuento</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-panel.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Datos de Panel</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Bibliografía</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page-right" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Modelos de Elección Discreta</span></h1>
</div>



<div class="quarto-title-meta column-page-right">

    
  
    
  </div>
  


</header>


<section id="introducción-por-qué-modelos-de-elección-discreta" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="introducción-por-qué-modelos-de-elección-discreta"><span class="header-section-number">3.1</span> Introducción: ¿por qué modelos de elección discreta?</h2>
<p>En muchas situaciones económicas, la variable que queremos explicar no es continua (como el salario o el PIB), sino que toma un número finito de valores. Los casos más habituales son las <strong>decisiones binarias</strong>:</p>
<ul>
<li>¿Trabaja esta persona o no? (<span class="math inline">\(y = 1\)</span> o <span class="math inline">\(y = 0\)</span>)</li>
<li>¿Se concede un crédito o se deniega?</li>
<li>¿Compra el consumidor el producto o no?</li>
</ul>
<p>Cuando la variable dependiente es binaria, el modelo de regresión lineal clásico (MCO) presenta <strong>problemas graves</strong>. Los modelos de elección discreta —Probit y Logit— resuelven estos problemas y son la herramienta estándar en microeconometría aplicada.</p>
<p>En estos apuntes seguiremos un hilo conductor muy claro:</p>
<ol type="1">
<li>Primero entenderemos los <strong>fundamentos estadísticos</strong> que hay detrás (variable aleatoria, densidad, distribución, verosimilitud).</li>
<li>Después veremos el <strong>Modelo Lineal de Probabilidad (MLP)</strong> y sus limitaciones.</li>
<li>A continuación, los modelos <strong>Probit</strong> y <strong>Logit</strong>, que resuelven esas limitaciones.</li>
<li>Finalmente, aprenderemos a <strong>interpretar</strong> los resultados (efectos marginales, odds ratios) y a <strong>evaluar</strong> la calidad del modelo (pseudo-R², contrastes).</li>
</ol>
<p>Todo se ilustrará con un ejemplo aplicado: la <strong>participación laboral</strong> en España.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="fundamentos-estadísticos" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="fundamentos-estadísticos"><span class="header-section-number">3.2</span> Fundamentos estadísticos</h2>
<p>Antes de estimar ningún modelo, necesitamos repasar cuatro conceptos clave que aparecen constantemente en el tema.</p>
<section id="variable-aleatoria" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="variable-aleatoria"><span class="header-section-number">3.2.1</span> Variable aleatoria</h3>
<p>Una <strong>variable aleatoria</strong> es una variable cuyo valor depende del resultado de un fenómeno aleatorio. En nuestro contexto:</p>
<p><span class="math display">\[y_i = \text{¿Trabaja la persona } i?\]</span></p>
<p>Antes de observar a la persona, <strong>no sabemos</strong> si <span class="math inline">\(y_i\)</span> será 0 o 1. Después de observarla, tenemos un dato fijo. La estadística nos permite modelar esa incertidumbre.</p>
<p>Hay dos tipos:</p>
<ul>
<li><strong>Discreta</strong>: toma valores contables (0, 1, 2, …). Ejemplo: <span class="math inline">\(y \in \{0, 1\}\)</span>.</li>
<li><strong>Continua</strong>: toma cualquier valor en un intervalo. Ejemplo: el salario.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-tipos-var-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Variable discreta (Bernoulli) y continua (Normal).</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="la-distribución-de-bernoulli" class="level3" data-number="3.2.2">
<h3 data-number="3.2.2" class="anchored" data-anchor-id="la-distribución-de-bernoulli"><span class="header-section-number">3.2.2</span> La distribución de Bernoulli</h3>
<p>Cuando <span class="math inline">\(y\)</span> solo puede ser 0 o 1, sigue una distribución <strong>Bernoulli(p)</strong>:</p>
<p><span class="math display">\[P(y = 1) = p \qquad\qquad P(y = 0) = 1 - p\]</span></p>
<p>En una sola expresión compacta:</p>
<p><span class="math display">\[\boxed{P(y) = p^{\,y} \cdot (1-p)^{1-y}}\]</span></p>
<p>Comprobación rápida:</p>
<ul>
<li>Si <span class="math inline">\(y = 1\)</span>: <span class="math inline">\(p^1 \cdot (1-p)^0 = p\)</span> ✓</li>
<li>Si <span class="math inline">\(y = 0\)</span>: <span class="math inline">\(p^0 \cdot (1-p)^1 = 1-p\)</span> ✓</li>
</ul>
<p>Esta fórmula compacta es <strong>exactamente</strong> la que aparece dentro de la función de verosimilitud (sección 2.5). La clave de todo el tema es que, en lugar de asumir que <span class="math inline">\(p\)</span> es la misma para todos los individuos, haremos que <strong>dependa de sus características</strong>: <span class="math inline">\(p_i = F(x_i'\beta)\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-bernoulli-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribución Bernoulli con distintos valores de p.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="función-de-densidad" class="level3" data-number="3.2.3">
<h3 data-number="3.2.3" class="anchored" data-anchor-id="función-de-densidad"><span class="header-section-number">3.2.3</span> Función de densidad</h3>
<p>Para variables <strong>continuas</strong>, no tiene sentido hablar de <span class="math inline">\(P(X = 2.317...)\)</span> (esa probabilidad es siempre cero). En su lugar usamos la <strong>función de densidad</strong> <span class="math inline">\(f(x)\)</span>:</p>
<p><span class="math display">\[P(a &lt; X &lt; b) = \int_a^b f(x)\, dx = \text{área bajo la curva}\]</span></p>
<p>La distribución continua más importante en estadística es la <strong>Normal</strong> (campana de Gauss):</p>
<p><span class="math display">\[f(x) = \frac{1}{\sqrt{2\pi}\,\sigma} \exp\!\left(-\frac{(x-\mu)^2}{2\sigma^2}\right)\]</span></p>
<p>La <strong>Normal estándar</strong> <span class="math inline">\(N(0,1)\)</span> — con <span class="math inline">\(\mu = 0\)</span> y <span class="math inline">\(\sigma = 1\)</span> — es la que utiliza el modelo <strong>Probit</strong>.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-densidad-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>La probabilidad es el área bajo la curva de densidad.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="función-de-distribución-acumulada-cdf" class="level3" data-number="3.2.4">
<h3 data-number="3.2.4" class="anchored" data-anchor-id="función-de-distribución-acumulada-cdf"><span class="header-section-number">3.2.4</span> Función de distribución acumulada (CDF)</h3>
<p>La <strong>CDF</strong> responde a la pregunta: <em>¿cuál es la probabilidad de obtener un valor</em> <span class="math inline">\(\leq x\)</span>?</p>
<p><span class="math display">\[F(x) = P(X \leq x) = \int_{-\infty}^{x} f(t)\, dt\]</span></p>
<p><strong>Propiedad fundamental</strong>: <span class="math inline">\(F(x)\)</span> siempre está en <span class="math inline">\([0, 1]\)</span>. Esto la hace <strong>perfecta para modelar probabilidades</strong>.</p>
<p>Cada modelo usa una CDF diferente:</p>
<ul>
<li><strong>Probit</strong> <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(\Phi(x'\beta)\)</span>, la CDF de la Normal estándar.</li>
<li><strong>Logit</strong> <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(\Lambda(x'\beta) = \frac{1}{1 + e^{-x'\beta}}\)</span>, la CDF de la distribución logística.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-cdf-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Densidad y distribución acumulada de la Normal estándar.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="la-verosimilitud-corazón-de-la-estimación" class="level3" data-number="3.2.5">
<h3 data-number="3.2.5" class="anchored" data-anchor-id="la-verosimilitud-corazón-de-la-estimación"><span class="header-section-number">3.2.5</span> La verosimilitud: corazón de la estimación</h3>
<section id="intuición" class="level4" data-number="3.2.5.1">
<h4 data-number="3.2.5.1" class="anchored" data-anchor-id="intuición"><span class="header-section-number">3.2.5.1</span> Intuición</h4>
<p>Imaginemos que lanzamos una moneda 3 veces y observamos: <strong>Cara, Cara, Cruz</strong>. ¿Cuál es la probabilidad <span class="math inline">\(p\)</span> de cara más compatible con este resultado?</p>
<p>La <strong>verosimilitud</strong> <span class="math inline">\(L(p)\)</span> mide exactamente eso: <em>dado un valor del parámetro, ¿qué tan probable es haber observado estos datos?</em></p>
<p><span class="math display">\[L(p) = p \cdot p \cdot (1-p) = p^2(1-p)\]</span></p>
<p>El <strong>estimador de máxima verosimilitud (MV)</strong> elige el valor de <span class="math inline">\(p\)</span> que maximiza <span class="math inline">\(L(p)\)</span>. En este ejemplo: <span class="math inline">\(\hat{p} = 2/3\)</span> (la proporción muestral de caras).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-verosimilitud-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Verosimilitud de observar [Cara, Cara, Cruz] según el parámetro p.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="de-la-verosimilitud-a-la-log-verosimilitud" class="level4" data-number="3.2.5.2">
<h4 data-number="3.2.5.2" class="anchored" data-anchor-id="de-la-verosimilitud-a-la-log-verosimilitud"><span class="header-section-number">3.2.5.2</span> De la verosimilitud a la log-verosimilitud</h4>
<p>Con <span class="math inline">\(N\)</span> observaciones independientes, la verosimilitud es un <strong>producto</strong>:</p>
<p><span class="math display">\[L(\beta) = \prod_{i=1}^N p_i^{\,y_i} \cdot (1-p_i)^{1-y_i}\]</span></p>
<p><strong>Problema práctico</strong>: multiplicar muchos números entre 0 y 1 produce números minúsculos que el ordenador no puede manejar (underflow numérico).</p>
<p><strong>Solución</strong>: tomar logaritmos. El logaritmo convierte el producto en suma, y <strong>el máximo se conserva</strong> (el logaritmo es una función creciente):</p>
<p><span class="math display">\[\boxed{\ln L(\beta) = \sum_{i=1}^N \left[ y_i \ln(p_i) + (1-y_i)\ln(1-p_i) \right]}\]</span></p>
<p>Esta es la <strong>función objetivo</strong> que maximizan Probit y Logit. El término <span class="math inline">\(ll_i = y_i \ln(p_i) + (1-y_i)\ln(1-p_i)\)</span> es la <strong>contribución</strong> del individuo <span class="math inline">\(i\)</span> a la log-verosimilitud:</p>
<ul>
<li>Si <span class="math inline">\(y_i = 1\)</span> y el modelo predice <span class="math inline">\(\hat{P}_i\)</span> alto <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(\ln(\hat{P}_i)\)</span> es cercano a 0 <span class="math inline">\(\rightarrow\)</span> <strong>bien</strong>.</li>
<li>Si <span class="math inline">\(y_i = 1\)</span> pero el modelo predice <span class="math inline">\(\hat{P}_i\)</span> bajo <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(\ln(\hat{P}_i)\)</span> es muy negativo <span class="math inline">\(\rightarrow\)</span> <strong>mal</strong>.</li>
</ul>
<p>El estimador MV busca los <span class="math inline">\(\beta\)</span> que hacen la log-verosimilitud <strong>lo menos negativa posible</strong>.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="el-modelo-lineal-de-probabilidad-mlp" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="el-modelo-lineal-de-probabilidad-mlp"><span class="header-section-number">3.3</span> El Modelo Lineal de Probabilidad (MLP)</h2>
<section id="planteamiento" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="planteamiento"><span class="header-section-number">3.3.1</span> Planteamiento</h3>
<p>El enfoque más simple para modelar una variable binaria es tratar <span class="math inline">\(y\)</span> como si fuera continua y aplicar MCO:</p>
<p><span class="math display">\[P(y_i = 1 \,|\, x_i) = x_i'\beta = \beta_0 + \beta_1 x_{1i} + \beta_2 x_{2i} + \cdots\]</span></p>
<p>Es decir, la probabilidad es una <strong>función lineal</strong> de las variables explicativas. Este modelo se llama <strong>Modelo Lineal de Probabilidad (MLP)</strong>.</p>
<p><strong>Ventaja</strong>: es extremadamente sencillo. Los coeficientes <strong>son directamente los efectos marginales</strong>: <span class="math inline">\(\beta_j\)</span> indica cuánto cambia la probabilidad al aumentar <span class="math inline">\(x_j\)</span> en una unidad.</p>
</section>
<section id="limitaciones-del-mlp" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="limitaciones-del-mlp"><span class="header-section-number">3.3.2</span> Limitaciones del MLP</h3>
<p>El MLP tiene <strong>tres problemas graves</strong>:</p>
<section id="problema-1-probabilidades-fuera-de-0-1" class="level4" data-number="3.3.2.1">
<h4 data-number="3.3.2.1" class="anchored" data-anchor-id="problema-1-probabilidades-fuera-de-0-1"><span class="header-section-number">3.3.2.1</span> Problema 1: Probabilidades fuera de [0, 1]</h4>
<p>Una recta puede tomar cualquier valor real. Nada impide que el modelo prediga <span class="math inline">\(\hat{P} = -0.15\)</span> o <span class="math inline">\(\hat{P} = 1.30\)</span>, lo cual <strong>no tiene sentido</strong> como probabilidad.</p>
</section>
<section id="problema-2-heterocedasticidad" class="level4" data-number="3.3.2.2">
<h4 data-number="3.3.2.2" class="anchored" data-anchor-id="problema-2-heterocedasticidad"><span class="header-section-number">3.3.2.2</span> Problema 2: Heterocedasticidad</h4>
<p>Si <span class="math inline">\(y \sim \text{Bernoulli}(p_i)\)</span>, entonces <span class="math inline">\(\text{Var}(\varepsilon_i) = p_i(1-p_i)\)</span>, que depende de <span class="math inline">\(x_i\)</span>. Los errores <strong>no son homocedásticos</strong>, lo que invalida la inferencia estándar (los errores estándar y los p-valores del MCO son incorrectos).</p>
</section>
<section id="problema-3-efecto-marginal-constante" class="level4" data-number="3.3.2.3">
<h4 data-number="3.3.2.3" class="anchored" data-anchor-id="problema-3-efecto-marginal-constante"><span class="header-section-number">3.3.2.3</span> Problema 3: Efecto marginal constante</h4>
<p>El MLP asume que el efecto de, por ejemplo, un año más de educación es <strong>siempre el mismo</strong>, independientemente de si la persona tiene 6 años o 18 años de educación. Económicamente, esto no es realista: el efecto debería ser mayor en la zona intermedia (donde hay más incertidumbre) y menor en los extremos (donde la decisión ya está prácticamente tomada).</p>
</section>
</section>
<section id="el-modelo-que-vamos-a-estimar" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="el-modelo-que-vamos-a-estimar"><span class="header-section-number">3.3.3</span> El modelo que vamos a estimar</h3>
<p>A lo largo de todo este tema utilizaremos un mismo modelo aplicado: la <strong>participación laboral</strong>. La variable dependiente es binaria:</p>
<p><span class="math display">\[y_i = \begin{cases} 1 &amp; \text{si la persona } i \text{ trabaja} \\ 0 &amp; \text{si no trabaja} \end{cases}\]</span></p>
<p>El modelo que estimaremos relaciona la probabilidad de trabajar con seis variables explicativas:</p>
<p><span class="math display">\[P(\text{trabaja}_i = 1) = F(\beta_0 + \beta_1 \, \text{educación}_i + \beta_2 \, \text{edad}_i + \beta_3 \, \text{sexo}_i + \beta_4 \, \text{experiencia}_i + \beta_5 \, \text{hijos}_i + \beta_6 \, \text{ingreso\_familiar}_i)\]</span></p>
<p>donde <span class="math inline">\(F(\cdot)\)</span> es la función de enlace: la identidad en el MLP, <span class="math inline">\(\Phi\)</span> en el Probit y <span class="math inline">\(\Lambda\)</span> en el Logit. Las variables son:</p>
<ul>
<li><strong>educación</strong>: años de educación completados.</li>
<li><strong>edad</strong>: edad en años.</li>
<li><strong>sexo</strong>: variable dummy (1 = Mujer, 0 = Hombre).</li>
<li><strong>experiencia</strong>: años de experiencia laboral.</li>
<li><strong>hijos</strong>: número de hijos menores de edad.</li>
<li><strong>ingreso_familiar</strong>: ingreso del hogar no procedente del trabajo del individuo (en miles de euros).</li>
</ul>
<p>Estimaremos este mismo modelo con los tres métodos (MLP, Probit, Logit) para poder comparar resultados.</p>
</section>
<section id="ejemplo-en-r" class="level3" data-number="3.3.4">
<h3 data-number="3.3.4" class="anchored" data-anchor-id="ejemplo-en-r"><span class="header-section-number">3.3.4</span> Ejemplo en R</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"participacion_laboral.csv"</span>, <span class="at">stringsAsFactors =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>mlp <span class="ot">&lt;-</span> <span class="fu">lm</span>(trabaja <span class="sc">~</span> educacion <span class="sc">+</span> edad <span class="sc">+</span> sexo <span class="sc">+</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>            experiencia <span class="sc">+</span> hijos <span class="sc">+</span> ingreso_familiar, <span class="at">data =</span> datos)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Tabla de coeficientes</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">round</span>(<span class="fu">summary</span>(mlp)<span class="sc">$</span>coefficients, <span class="dv">4</span>),</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Coeficientes del MLP (estimados por MCO)"</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">escape =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Coeficientes del MLP (estimados por MCO)</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">t value</th>
<th style="text-align: right;">Pr(&gt;|t|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.0454</td>
<td style="text-align: right;">0.0933</td>
<td style="text-align: right;">0.4861</td>
<td style="text-align: right;">0.6271</td>
</tr>
<tr class="even">
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">0.0231</td>
<td style="text-align: right;">0.0068</td>
<td style="text-align: right;">3.3869</td>
<td style="text-align: right;">0.0008</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">0.0127</td>
<td style="text-align: right;">0.0059</td>
<td style="text-align: right;">2.1554</td>
<td style="text-align: right;">0.0316</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexoMujer</td>
<td style="text-align: right;">-0.0870</td>
<td style="text-align: right;">0.0342</td>
<td style="text-align: right;">-2.5405</td>
<td style="text-align: right;">0.0114</td>
</tr>
<tr class="odd">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">0.0011</td>
<td style="text-align: right;">0.0058</td>
<td style="text-align: right;">0.1838</td>
<td style="text-align: right;">0.8542</td>
</tr>
<tr class="even">
<td style="text-align: left;">hijos</td>
<td style="text-align: right;">-0.0433</td>
<td style="text-align: right;">0.0145</td>
<td style="text-align: right;">-2.9832</td>
<td style="text-align: right;">0.0030</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ingreso_familiar</td>
<td style="text-align: right;">-0.0054</td>
<td style="text-align: right;">0.0030</td>
<td style="text-align: right;">-1.7924</td>
<td style="text-align: right;">0.0737</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Interpretación</strong> (recuerda: en el MLP, los coeficientes = efectos marginales):</p>
<ul>
<li><strong>educación</strong>: un año más de educación aumenta la probabilidad de trabajar en 2.3 puntos porcentuales.</li>
<li><strong>sexo (Mujer)</strong>: ser mujer reduce la probabilidad en 8.7 pp.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-mlp-problemas-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Limitaciones del MLP: predicciones fuera de [0,1] y efecto marginal constante.</figcaption>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Conclusión</strong>: El MLP sirve como referencia rápida, pero sus limitaciones teóricas son serias. Necesitamos modelos que <strong>garanticen</strong> <span class="math inline">\(\hat{P} \in [0, 1]\)</span> y capturen la no linealidad. Esos modelos son el Probit y el Logit.</p>
</blockquote>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="el-modelo-probit" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="el-modelo-probit"><span class="header-section-number">3.4</span> El modelo Probit</h2>
<section id="planteamiento-1" class="level3" data-number="3.4.1">
<h3 data-number="3.4.1" class="anchored" data-anchor-id="planteamiento-1"><span class="header-section-number">3.4.1</span> Planteamiento</h3>
<p>El modelo Probit resuelve los tres problemas del MLP <strong>envolviendo</strong> el índice lineal <span class="math inline">\(x'\beta\)</span> con la CDF de la Normal estándar <span class="math inline">\(\Phi(\cdot)\)</span>:</p>
<p><span class="math display">\[\boxed{P(y_i = 1 \,|\, x_i) = \Phi(x_i'\beta) = \Phi(\beta_0 + \beta_1 x_{1i} + \cdots)}\]</span></p>
<p>donde <span class="math inline">\(\Phi(z) = \int_{-\infty}^{z} \frac{1}{\sqrt{2\pi}} e^{-t^2/2}\, dt\)</span></p>
<p>Dado que <span class="math inline">\(\Phi(\cdot)\)</span> siempre devuelve valores en <span class="math inline">\([0, 1]\)</span>, <strong>las predicciones siempre son probabilidades válidas</strong>.</p>
<section id="cómo-se-estima" class="level4" data-number="3.4.1.1">
<h4 data-number="3.4.1.1" class="anchored" data-anchor-id="cómo-se-estima"><span class="header-section-number">3.4.1.1</span> ¿Cómo se estima?</h4>
<p><strong>No por MCO</strong>, sino por <strong>máxima verosimilitud (MV)</strong>. Se buscan los <span class="math inline">\(\hat{\beta}\)</span> que maximizan:</p>
<p><span class="math display">\[\ln L(\beta) = \sum_{i=1}^N \left[ y_i \ln\Phi(x_i'\beta) + (1-y_i)\ln(1-\Phi(x_i'\beta)) \right]\]</span></p>
<p>Este problema no tiene solución cerrada — se resuelve numéricamente mediante algoritmos iterativos (Newton-Raphson, BFGS, etc.). En R, la función <code>glm()</code> hace todo el trabajo.</p>
</section>
</section>
<section id="estimación-en-r" class="level3" data-number="3.4.2">
<h3 data-number="3.4.2" class="anchored" data-anchor-id="estimación-en-r"><span class="header-section-number">3.4.2</span> Estimación en R</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>probit <span class="ot">&lt;-</span> <span class="fu">glm</span>(trabaja <span class="sc">~</span> educacion <span class="sc">+</span> edad <span class="sc">+</span> sexo <span class="sc">+</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                experiencia <span class="sc">+</span> hijos <span class="sc">+</span> ingreso_familiar,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> datos, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"probit"</span>))</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">round</span>(<span class="fu">summary</span>(probit)<span class="sc">$</span>coefficients, <span class="dv">4</span>),</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Coeficientes del modelo Probit (estimados por MV)"</span>, <span class="at">escape =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Coeficientes del modelo Probit (estimados por MV)</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">z value</th>
<th style="text-align: right;">Pr(&gt;|z|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-1.9298</td>
<td style="text-align: right;">0.3865</td>
<td style="text-align: right;">-4.9927</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">0.0924</td>
<td style="text-align: right;">0.0274</td>
<td style="text-align: right;">3.3751</td>
<td style="text-align: right;">0.0007</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">0.0536</td>
<td style="text-align: right;">0.0240</td>
<td style="text-align: right;">2.2352</td>
<td style="text-align: right;">0.0254</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexoMujer</td>
<td style="text-align: right;">-0.3457</td>
<td style="text-align: right;">0.1409</td>
<td style="text-align: right;">-2.4534</td>
<td style="text-align: right;">0.0142</td>
</tr>
<tr class="odd">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">0.0234</td>
<td style="text-align: right;">0.0008</td>
<td style="text-align: right;">0.9993</td>
</tr>
<tr class="even">
<td style="text-align: left;">hijos</td>
<td style="text-align: right;">-0.1837</td>
<td style="text-align: right;">0.0585</td>
<td style="text-align: right;">-3.1417</td>
<td style="text-align: right;">0.0017</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ingreso_familiar</td>
<td style="text-align: right;">-0.0233</td>
<td style="text-align: right;">0.0124</td>
<td style="text-align: right;">-1.8853</td>
<td style="text-align: right;">0.0594</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="cómo-se-interpretan-los-coeficientes" class="level4" data-number="3.4.2.1">
<h4 data-number="3.4.2.1" class="anchored" data-anchor-id="cómo-se-interpretan-los-coeficientes"><span class="header-section-number">3.4.2.1</span> ¿Cómo se interpretan los coeficientes?</h4>
<p><strong>¡Cuidado!</strong> A diferencia del MLP, los coeficientes del Probit <strong>NO</strong> son efectos marginales. Solo nos dicen la <strong>dirección</strong> del efecto:</p>
<ul>
<li><span class="math inline">\(\hat{\beta}_j &gt; 0\)</span> <span class="math inline">\(\rightarrow\)</span> la variable <span class="math inline">\(x_j\)</span> <strong>aumenta</strong> la probabilidad.</li>
<li><span class="math inline">\(\hat{\beta}_j &lt; 0\)</span> <span class="math inline">\(\rightarrow\)</span> la variable <span class="math inline">\(x_j\)</span> <strong>disminuye</strong> la probabilidad.</li>
</ul>
<p>Para saber <strong>cuánto</strong> cambia la probabilidad, necesitamos calcular los <strong>efectos marginales</strong> (sección 6).</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="el-modelo-logit" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="el-modelo-logit"><span class="header-section-number">3.5</span> El modelo Logit</h2>
<section id="planteamiento-2" class="level3" data-number="3.5.1">
<h3 data-number="3.5.1" class="anchored" data-anchor-id="planteamiento-2"><span class="header-section-number">3.5.1</span> Planteamiento</h3>
<p>El modelo Logit es conceptualmente idéntico al Probit, pero usa la <strong>función logística</strong> <span class="math inline">\(\Lambda(\cdot)\)</span> en lugar de la Normal:</p>
<p><span class="math display">\[\boxed{P(y_i = 1 \,|\, x_i) = \Lambda(x_i'\beta) = \frac{1}{1 + e^{-x_i'\beta}} = \frac{e^{x_i'\beta}}{1 + e^{x_i'\beta}}}\]</span></p>
<section id="ventajas-del-logit-respecto-al-probit" class="level4" data-number="3.5.1.1">
<h4 data-number="3.5.1.1" class="anchored" data-anchor-id="ventajas-del-logit-respecto-al-probit"><span class="header-section-number">3.5.1.1</span> Ventajas del Logit respecto al Probit</h4>
<ol type="1">
<li><strong>Fórmula cerrada</strong>: <span class="math inline">\(\Lambda(z) = 1/(1+e^{-z})\)</span> se calcula directamente, sin integrales.</li>
<li><strong>Interpretación vía odds ratios</strong>: los coeficientes tienen una interpretación directa en términos de log-odds (veremos esto en la sección 7).</li>
<li><strong>El más usado</strong> en la práctica por estas dos razones.</li>
</ol>
</section>
<section id="logit-vs-probit-cuál-elegir" class="level4" data-number="3.5.1.2">
<h4 data-number="3.5.1.2" class="anchored" data-anchor-id="logit-vs-probit-cuál-elegir"><span class="header-section-number">3.5.1.2</span> Logit vs Probit: ¿cuál elegir?</h4>
<p>En la práctica, ambos producen resultados <strong>prácticamente idénticos</strong>. La función logística y la Normal acumulada son casi iguales en el rango central, donde se concentra la mayoría de los datos. Solo difieren ligeramente en las colas (la logística tiene colas más gruesas).</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-logit-vs-probit-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Logit y Probit son casi idénticos en el rango central.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Regla práctica</strong>: la elección entre Logit y Probit es una <strong>convención</strong> del área de investigación. En economía del trabajo y salud suele usarse Probit; en marketing, finanzas y machine learning se prefiere Logit.</p>
</section>
</section>
<section id="estimación-en-r-1" class="level3" data-number="3.5.2">
<h3 data-number="3.5.2" class="anchored" data-anchor-id="estimación-en-r-1"><span class="header-section-number">3.5.2</span> Estimación en R</h3>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>logit <span class="ot">&lt;-</span> <span class="fu">glm</span>(trabaja <span class="sc">~</span> educacion <span class="sc">+</span> edad <span class="sc">+</span> sexo <span class="sc">+</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>               experiencia <span class="sc">+</span> hijos <span class="sc">+</span> ingreso_familiar,</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">data =</span> datos, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link =</span> <span class="st">"logit"</span>))</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">round</span>(<span class="fu">summary</span>(logit)<span class="sc">$</span>coefficients, <span class="dv">4</span>),</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>             <span class="at">caption =</span> <span class="st">"Coeficientes del modelo Logit (estimados por MV)"</span>, <span class="at">escape =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Coeficientes del modelo Logit (estimados por MV)</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Estimate</th>
<th style="text-align: right;">Std. Error</th>
<th style="text-align: right;">z value</th>
<th style="text-align: right;">Pr(&gt;|z|)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">-3.3250</td>
<td style="text-align: right;">0.6825</td>
<td style="text-align: right;">-4.8721</td>
<td style="text-align: right;">0.0000</td>
</tr>
<tr class="even">
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">0.1586</td>
<td style="text-align: right;">0.0481</td>
<td style="text-align: right;">3.3008</td>
<td style="text-align: right;">0.0010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">0.0932</td>
<td style="text-align: right;">0.0422</td>
<td style="text-align: right;">2.2073</td>
<td style="text-align: right;">0.0273</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexoMujer</td>
<td style="text-align: right;">-0.6437</td>
<td style="text-align: right;">0.2477</td>
<td style="text-align: right;">-2.5989</td>
<td style="text-align: right;">0.0094</td>
</tr>
<tr class="odd">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">0.0012</td>
<td style="text-align: right;">0.0412</td>
<td style="text-align: right;">0.0290</td>
<td style="text-align: right;">0.9769</td>
</tr>
<tr class="even">
<td style="text-align: left;">hijos</td>
<td style="text-align: right;">-0.3111</td>
<td style="text-align: right;">0.1024</td>
<td style="text-align: right;">-3.0366</td>
<td style="text-align: right;">0.0024</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ingreso_familiar</td>
<td style="text-align: right;">-0.0434</td>
<td style="text-align: right;">0.0216</td>
<td style="text-align: right;">-2.0052</td>
<td style="text-align: right;">0.0449</td>
</tr>
</tbody>
</table>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="el-flujo-completo-de-las-x-a-la-probabilidad" class="level2" data-number="3.6">
<h2 data-number="3.6" class="anchored" data-anchor-id="el-flujo-completo-de-las-x-a-la-probabilidad"><span class="header-section-number">3.6</span> El flujo completo: de las X a la probabilidad</h2>
<p>Para que quede completamente claro cómo funcionan estos modelos, veamos el flujo paso a paso:</p>
<p><strong>PASO 1 — Índice lineal</strong>: se calcula <span class="math inline">\(x_i'\hat{\beta} = \hat{\beta}_0 + \hat{\beta}_1 x_{1i} + \cdots\)</span> (esto es como el <span class="math inline">\(\hat{y}\)</span> del MCO).</p>
<p><strong>PASO 2 — Función de enlace</strong>: el índice se “pasa” por la función <span class="math inline">\(F(\cdot)\)</span>: <span class="math inline">\(\Phi\)</span> para Probit o <span class="math inline">\(\Lambda\)</span> para Logit.</p>
<p><strong>PASO 3 — Probabilidad</strong>: el resultado es <span class="math inline">\(\hat{P}_i = F(x_i'\hat{\beta}) \in [0, 1]\)</span>.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-flujo-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Del índice lineal a la probabilidad: el flujo completo.</figcaption>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="efectos-marginales" class="level2" data-number="3.7">
<h2 data-number="3.7" class="anchored" data-anchor-id="efectos-marginales"><span class="header-section-number">3.7</span> Efectos marginales</h2>
<section id="el-problema-qué-significan-realmente-los-coeficientes" class="level3" data-number="3.7.1">
<h3 data-number="3.7.1" class="anchored" data-anchor-id="el-problema-qué-significan-realmente-los-coeficientes"><span class="header-section-number">3.7.1</span> El problema: ¿qué significan realmente los coeficientes?</h3>
<p>Empecemos con una pregunta concreta. Hemos estimado el modelo Logit y obtenemos <span class="math inline">\(\hat{\beta}_{\text{educacion}} = 0.35\)</span>. Un alumno pregunta: <em>“¿Entonces un año más de educación aumenta la probabilidad de trabajar en 0.35?”</em></p>
<p><strong>La respuesta es NO.</strong> Y entender por qué es la clave de toda esta sección.</p>
<section id="en-el-mlp-sí-funcionaba-así" class="level4" data-number="3.7.1.1">
<h4 data-number="3.7.1.1" class="anchored" data-anchor-id="en-el-mlp-sí-funcionaba-así"><span class="header-section-number">3.7.1.1</span> En el MLP sí funcionaba así</h4>
<p>En el MLP (regresión lineal), el modelo es:</p>
<p><span class="math display">\[P(y_i = 1) = \beta_0 + \beta_1 \cdot \text{educacion}_i + \cdots\]</span></p>
<p>Si <span class="math inline">\(\beta_1 = 0.04\)</span>, entonces un año más de educación <strong>siempre</strong> aumenta la probabilidad en 0.04 (4 puntos porcentuales), sin importar nada más. El efecto es <strong>constante</strong>.</p>
</section>
<section id="en-el-logitprobit-ya-no-funciona-así" class="level4" data-number="3.7.1.2">
<h4 data-number="3.7.1.2" class="anchored" data-anchor-id="en-el-logitprobit-ya-no-funciona-así"><span class="header-section-number">3.7.1.2</span> En el Logit/Probit ya no funciona así</h4>
<p>En el Logit, el modelo es:</p>
<p><span class="math display">\[P(y_i = 1) = \Lambda(\beta_0 + \beta_1 \cdot \text{educacion}_i + \cdots)\]</span></p>
<p>La función <span class="math inline">\(\Lambda(\cdot)\)</span> es una curva en forma de S, <strong>no</strong> una recta. Por eso, el efecto de un año más de educación <strong>depende de dónde estés en la curva</strong>.</p>
</section>
</section>
<section id="ejemplo-numérico-paso-a-paso" class="level3" data-number="3.7.2">
<h3 data-number="3.7.2" class="anchored" data-anchor-id="ejemplo-numérico-paso-a-paso"><span class="header-section-number">3.7.2</span> Ejemplo numérico paso a paso</h3>
<p>Veamos esto con números concretos. Supongamos un modelo Logit simple:</p>
<p><span class="math display">\[P(\text{trabaja} = 1) = \Lambda(-3 + 0.25 \cdot \text{educacion})\]</span></p>
<section id="persona-a-8-años-de-educación-nivel-bajo" class="level4" data-number="3.7.2.1">
<h4 data-number="3.7.2.1" class="anchored" data-anchor-id="persona-a-8-años-de-educación-nivel-bajo"><span class="header-section-number">3.7.2.1</span> Persona A: 8 años de educación (nivel bajo)</h4>
<p><span class="math display">\[x'\beta = -3 + 0.25 \times 8 = -1.0 \qquad \Rightarrow \qquad P = \Lambda(-1.0) = \frac{1}{1+e^{1}} = 0.269\]</span></p>
<p>Si pasa a <strong>9 años</strong>: <span class="math display">\[x'\beta = -3 + 0.25 \times 9 = -0.75 \qquad \Rightarrow \qquad P = \Lambda(-0.75) = 0.321\]</span></p>
<p><strong>Efecto marginal</strong> = 0.321 − 0.269 = <strong>+5.2 puntos porcentuales</strong>.</p>
</section>
<section id="persona-b-12-años-de-educación-nivel-medio" class="level4" data-number="3.7.2.2">
<h4 data-number="3.7.2.2" class="anchored" data-anchor-id="persona-b-12-años-de-educación-nivel-medio"><span class="header-section-number">3.7.2.2</span> Persona B: 12 años de educación (nivel medio)</h4>
<p><span class="math display">\[x'\beta = -3 + 0.25 \times 12 = 0.0 \qquad \Rightarrow \qquad P = \Lambda(0) = 0.500\]</span></p>
<p>Si pasa a <strong>13 años</strong>: <span class="math display">\[x'\beta = -3 + 0.25 \times 13 = 0.25 \qquad \Rightarrow \qquad P = \Lambda(0.25) = 0.562\]</span></p>
<p><strong>Efecto marginal</strong> = 0.562 − 0.500 = <strong>+6.2 puntos porcentuales</strong>.</p>
</section>
<section id="persona-c-18-años-de-educación-nivel-alto" class="level4" data-number="3.7.2.3">
<h4 data-number="3.7.2.3" class="anchored" data-anchor-id="persona-c-18-años-de-educación-nivel-alto"><span class="header-section-number">3.7.2.3</span> Persona C: 18 años de educación (nivel alto)</h4>
<p><span class="math display">\[x'\beta = -3 + 0.25 \times 18 = 1.5 \qquad \Rightarrow \qquad P = \Lambda(1.5) = 0.818\]</span></p>
<p>Si pasa a <strong>19 años</strong>: <span class="math display">\[x'\beta = -3 + 0.25 \times 19 = 1.75 \qquad \Rightarrow \qquad P = \Lambda(1.75) = 0.852\]</span></p>
<p><strong>Efecto marginal</strong> = 0.852 − 0.818 = <strong>+3.4 puntos porcentuales</strong>.</p>
</section>
<section id="qué-acabamos-de-ver" class="level4" data-number="3.7.2.4">
<h4 data-number="3.7.2.4" class="anchored" data-anchor-id="qué-acabamos-de-ver"><span class="header-section-number">3.7.2.4</span> ¿Qué acabamos de ver?</h4>
<p>El mismo cambio (+1 año de educación) produce efectos <strong>muy diferentes</strong> según el punto de partida:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 28%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Persona</th>
<th style="text-align: center;">Educación</th>
<th style="text-align: center;">P antes</th>
<th style="text-align: center;">P después</th>
<th style="text-align: center;">Efecto marginal</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">A (nivel bajo)</td>
<td style="text-align: center;">8 <span class="math inline">\(\rightarrow\)</span> 9</td>
<td style="text-align: center;">26.9%</td>
<td style="text-align: center;">32.1%</td>
<td style="text-align: center;"><strong>+5.2 pp</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">B (nivel medio)</td>
<td style="text-align: center;">12 <span class="math inline">\(\rightarrow\)</span> 13</td>
<td style="text-align: center;">50.0%</td>
<td style="text-align: center;">56.2%</td>
<td style="text-align: center;"><strong>+6.2 pp</strong></td>
</tr>
<tr class="odd">
<td style="text-align: center;">C (nivel alto)</td>
<td style="text-align: center;">18 <span class="math inline">\(\rightarrow\)</span> 19</td>
<td style="text-align: center;">81.8%</td>
<td style="text-align: center;">85.2%</td>
<td style="text-align: center;"><strong>+3.4 pp</strong></td>
</tr>
</tbody>
</table>
<p><strong>El efecto es máximo en la zona intermedia</strong> (donde <span class="math inline">\(P \approx 0.5\)</span>) y se reduce en los extremos. Esto tiene todo el sentido económico: si alguien ya tiene un 95% de probabilidad de trabajar, un año más de educación apenas puede subirla; pero si está en el 50%, el mismo año puede marcar una gran diferencia.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Modelo Logit simple: P = Lambda(-3 + 0.25 * educacion)</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">3</span>;  b1 <span class="ot">&lt;-</span> <span class="fl">0.25</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>edu_seq <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">4</span>, <span class="dv">22</span>, <span class="at">length.out =</span> <span class="dv">300</span>)</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>prob_seq <span class="ot">&lt;-</span> <span class="fu">plogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> edu_seq)</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="fl">4.5</span>, <span class="fl">3.5</span>, <span class="dv">1</span>))</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="do">## --- Panel izquierdo: la curva y los tres puntos ---</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(edu_seq, prob_seq, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"#3498DB"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Años de educación"</span>, <span class="at">ylab =</span> <span class="st">"P(trabaja = 1)"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Curva Logit: el efecto depende</span><span class="sc">\n</span><span class="st">del punto de partida"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fl">0.5</span>, <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"grey60"</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="do">## Persona A (8 años)</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>p_A0 <span class="ot">&lt;-</span> <span class="fu">plogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> <span class="dv">8</span>);  p_A1 <span class="ot">&lt;-</span> <span class="fu">plogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> <span class="dv">9</span>)</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(<span class="dv">8</span>, p_A0, <span class="dv">9</span>, p_A1, <span class="at">col =</span> <span class="st">"#E74C3C"</span>, <span class="at">lwd =</span> <span class="fl">2.5</span>, <span class="at">length =</span> <span class="fl">0.08</span>)</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">8</span>, p_A0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#E74C3C"</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">9.3</span>, (p_A0<span class="sc">+</span>p_A1)<span class="sc">/</span><span class="dv">2</span>, <span class="fu">sprintf</span>(<span class="st">"+%.1f pp"</span>, (p_A1<span class="sc">-</span>p_A0)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"#C0392B"</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">0.85</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a><span class="do">## Persona B (12 años)</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>p_B0 <span class="ot">&lt;-</span> <span class="fu">plogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> <span class="dv">12</span>); p_B1 <span class="ot">&lt;-</span> <span class="fu">plogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> <span class="dv">13</span>)</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(<span class="dv">12</span>, p_B0, <span class="dv">13</span>, p_B1, <span class="at">col =</span> <span class="st">"#27AE60"</span>, <span class="at">lwd =</span> <span class="fl">2.5</span>, <span class="at">length =</span> <span class="fl">0.08</span>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">12</span>, p_B0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#27AE60"</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">13.3</span>, (p_B0<span class="sc">+</span>p_B1)<span class="sc">/</span><span class="dv">2</span>, <span class="fu">sprintf</span>(<span class="st">"+%.1f pp"</span>, (p_B1<span class="sc">-</span>p_B0)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"#1E8449"</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">0.85</span>)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a><span class="do">## Persona C (18 años)</span></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>p_C0 <span class="ot">&lt;-</span> <span class="fu">plogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> <span class="dv">18</span>); p_C1 <span class="ot">&lt;-</span> <span class="fu">plogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> <span class="dv">19</span>)</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a><span class="fu">arrows</span>(<span class="dv">18</span>, p_C0, <span class="dv">19</span>, p_C1, <span class="at">col =</span> <span class="st">"#8E44AD"</span>, <span class="at">lwd =</span> <span class="fl">2.5</span>, <span class="at">length =</span> <span class="fl">0.08</span>)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">18</span>, p_C0, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#8E44AD"</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="fl">19.3</span>, (p_C0<span class="sc">+</span>p_C1)<span class="sc">/</span><span class="dv">2</span>, <span class="fu">sprintf</span>(<span class="st">"+%.1f pp"</span>, (p_C1<span class="sc">-</span>p_C0)<span class="sc">*</span><span class="dv">100</span>),</span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"#6C3483"</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">0.85</span>)</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">bty =</span> <span class="st">"n"</span>, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">pt.cex =</span> <span class="fl">1.3</span>,</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"#E74C3C"</span>, <span class="st">"#27AE60"</span>, <span class="st">"#8E44AD"</span>),</span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"A: 8 años (nivel bajo)"</span>,</span>
<span id="cb4-39"><a href="#cb4-39" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"B: 12 años (nivel medio)"</span>,</span>
<span id="cb4-40"><a href="#cb4-40" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"C: 18 años (nivel alto)"</span>), <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb4-41"><a href="#cb4-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-42"><a href="#cb4-42" aria-hidden="true" tabindex="-1"></a><span class="do">## --- Panel derecho: efecto marginal en cada punto ---</span></span>
<span id="cb4-43"><a href="#cb4-43" aria-hidden="true" tabindex="-1"></a>edu_grid <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">4</span>, <span class="dv">22</span>, <span class="at">length.out =</span> <span class="dv">200</span>)</span>
<span id="cb4-44"><a href="#cb4-44" aria-hidden="true" tabindex="-1"></a>me_grid  <span class="ot">&lt;-</span> <span class="fu">dlogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> edu_grid) <span class="sc">*</span> b1 <span class="sc">*</span> <span class="dv">100</span>   <span class="co"># en pp</span></span>
<span id="cb4-45"><a href="#cb4-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-46"><a href="#cb4-46" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(edu_grid, me_grid, <span class="at">type =</span> <span class="st">"l"</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">"#2C3E50"</span>,</span>
<span id="cb4-47"><a href="#cb4-47" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Años de educación"</span>,</span>
<span id="cb4-48"><a href="#cb4-48" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Efecto marginal (pp por año adicional)"</span>,</span>
<span id="cb4-49"><a href="#cb4-49" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"El efecto marginal cambia</span><span class="sc">\n</span><span class="st">según la educación de partida"</span>)</span>
<span id="cb4-50"><a href="#cb4-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-51"><a href="#cb4-51" aria-hidden="true" tabindex="-1"></a><span class="do">## Marcar los tres puntos</span></span>
<span id="cb4-52"><a href="#cb4-52" aria-hidden="true" tabindex="-1"></a>me_A <span class="ot">&lt;-</span> <span class="fu">dlogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> <span class="dv">8</span>)  <span class="sc">*</span> b1 <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb4-53"><a href="#cb4-53" aria-hidden="true" tabindex="-1"></a>me_B <span class="ot">&lt;-</span> <span class="fu">dlogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> <span class="dv">12</span>) <span class="sc">*</span> b1 <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb4-54"><a href="#cb4-54" aria-hidden="true" tabindex="-1"></a>me_C <span class="ot">&lt;-</span> <span class="fu">dlogis</span>(b0 <span class="sc">+</span> b1 <span class="sc">*</span> <span class="dv">18</span>) <span class="sc">*</span> b1 <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb4-55"><a href="#cb4-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-56"><a href="#cb4-56" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">8</span>,  me_A, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#E74C3C"</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb4-57"><a href="#cb4-57" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">12</span>, me_B, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#27AE60"</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb4-58"><a href="#cb4-58" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">18</span>, me_C, <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">col =</span> <span class="st">"#8E44AD"</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb4-59"><a href="#cb4-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-60"><a href="#cb4-60" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">8</span>,  me_A <span class="sc">+</span> <span class="fl">0.25</span>, <span class="fu">sprintf</span>(<span class="st">"A: %.1f pp"</span>, me_A), <span class="at">col =</span> <span class="st">"#C0392B"</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb4-61"><a href="#cb4-61" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">12</span>, me_B <span class="sc">+</span> <span class="fl">0.25</span>, <span class="fu">sprintf</span>(<span class="st">"B: %.1f pp"</span>, me_B), <span class="at">col =</span> <span class="st">"#1E8449"</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb4-62"><a href="#cb4-62" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">18</span>, me_C <span class="sc">+</span> <span class="fl">0.25</span>, <span class="fu">sprintf</span>(<span class="st">"C: %.1f pp"</span>, me_C), <span class="at">col =</span> <span class="st">"#6C3483"</span>, <span class="at">font =</span> <span class="dv">2</span>, <span class="at">cex =</span> <span class="fl">0.8</span>)</span>
<span id="cb4-63"><a href="#cb4-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-64"><a href="#cb4-64" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h =</span> <span class="fu">mean</span>(me_grid), <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"grey50"</span>)</span>
<span id="cb4-65"><a href="#cb4-65" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">20</span>, <span class="fu">mean</span>(me_grid) <span class="sc">+</span> <span class="fl">0.2</span>, <span class="st">"Media"</span>, <span class="at">col =</span> <span class="st">"grey40"</span>, <span class="at">cex =</span> <span class="fl">0.75</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-me-ejemplo-numerico-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>El efecto de +1 año de educación depende del punto de partida: máximo en la zona intermedia, mínimo en los extremos.</figcaption>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="la-fórmula-general-del-efecto-marginal" class="level3" data-number="3.7.3">
<h3 data-number="3.7.3" class="anchored" data-anchor-id="la-fórmula-general-del-efecto-marginal"><span class="header-section-number">3.7.3</span> La fórmula general del efecto marginal</h3>
<p>Lo que acabamos de ver con las tres personas tiene una fórmula exacta. Recordemos qué hicimos: para cada persona calculamos la probabilidad <em>antes</em> y <em>después</em> de añadir un año de educación, y restamos. Eso es una aproximación discreta de la <strong>derivada parcial</strong>:</p>
<p><span class="math display">\[\boxed{\frac{\partial P(y=1)}{\partial x_j} = f(x'\beta) \cdot \beta_j}\]</span></p>
<p>Vamos a desmontar esta fórmula pieza a pieza:</p>
<p><strong>Pieza 1:</strong> <span class="math inline">\(\beta_j\)</span> — es el coeficiente estimado de la variable <span class="math inline">\(x_j\)</span>. Nos dice la <strong>dirección</strong> del efecto (positivo o negativo) y su <strong>intensidad en la escala latente</strong> (en el mundo del índice <span class="math inline">\(x'\beta\)</span>).</p>
<p><strong>Pieza 2:</strong> <span class="math inline">\(f(x'\beta)\)</span> — es un <strong>factor de escala</strong> que “traduce” el efecto del mundo latente al mundo de las probabilidades. Este factor <strong>cambia de persona a persona</strong> porque depende de <span class="math inline">\(x'\beta\)</span>, es decir, de las características de cada individuo.</p>
<p>¿Qué es exactamente <span class="math inline">\(f\)</span>? Es la <strong>función de densidad</strong> que corresponde a la CDF del modelo:</p>
<ul>
<li>En el <strong>Logit</strong>, la CDF es <span class="math inline">\(\Lambda(z)\)</span>, y su densidad es <span class="math inline">\(f(z) = \Lambda(z) \cdot [1 - \Lambda(z)] = P \cdot (1-P)\)</span>.</li>
<li>En el <strong>Probit</strong>, la CDF es <span class="math inline">\(\Phi(z)\)</span>, y su densidad es <span class="math inline">\(f(z) = \phi(z)\)</span> (la campana de Gauss).</li>
<li>En el <strong>MLP</strong>, la CDF es la identidad, y su “densidad” es <span class="math inline">\(f = 1\)</span> siempre. Por eso en el MLP el efecto marginal es simplemente <span class="math inline">\(\beta_j\)</span>.</li>
</ul>
<section id="cuánto-vale-ese-factor-de-escala" class="level4" data-number="3.7.3.1">
<h4 data-number="3.7.3.1" class="anchored" data-anchor-id="cuánto-vale-ese-factor-de-escala"><span class="header-section-number">3.7.3.1</span> ¿Cuánto vale ese factor de escala?</h4>
<p>Veámoslo con el ejemplo del Logit. El factor es <span class="math inline">\(f(z) = P(1-P)\)</span>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 37%">
<col style="width: 39%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Probabilidad <span class="math inline">\(P\)</span> del individuo</th>
<th style="text-align: center;">Factor <span class="math inline">\(f = P(1-P)\)</span></th>
<th style="text-align: left;">¿Grande o pequeño?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.05 (casi seguro que no trabaja)</td>
<td style="text-align: center;"><span class="math inline">\(0.05 \times 0.95 = 0.048\)</span></td>
<td style="text-align: left;">Muy pequeño</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.25</td>
<td style="text-align: center;"><span class="math inline">\(0.25 \times 0.75 = 0.188\)</span></td>
<td style="text-align: left;">Moderado</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><strong>0.50</strong> (máxima incertidumbre)</td>
<td style="text-align: center;"><span class="math inline">\(0.50 \times 0.50 = \mathbf{0.250}\)</span></td>
<td style="text-align: left;"><strong>Máximo</strong></td>
</tr>
<tr class="even">
<td style="text-align: center;">0.75</td>
<td style="text-align: center;"><span class="math inline">\(0.75 \times 0.25 = 0.188\)</span></td>
<td style="text-align: left;">Moderado</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.95 (casi seguro que trabaja)</td>
<td style="text-align: center;"><span class="math inline">\(0.95 \times 0.05 = 0.048\)</span></td>
<td style="text-align: left;">Muy pequeño</td>
</tr>
</tbody>
</table>
<p><strong>Intuición clave</strong>: el factor es máximo cuando <span class="math inline">\(P = 0.50\)</span> (máxima incertidumbre) y se acerca a cero en los extremos. Esto significa que <strong>un año más de educación “mueve” más la probabilidad de las personas que están en la zona de duda</strong> que de las que ya tienen la decisión prácticamente tomada.</p>
</section>
<section id="volviendo-al-ejemplo-numérico" class="level4" data-number="3.7.3.2">
<h4 data-number="3.7.3.2" class="anchored" data-anchor-id="volviendo-al-ejemplo-numérico"><span class="header-section-number">3.7.3.2</span> Volviendo al ejemplo numérico</h4>
<p>Retomemos las tres personas con <span class="math inline">\(\beta_{\text{educacion}} = 0.25\)</span>:</p>
<ul>
<li><strong>Persona A</strong> (<span class="math inline">\(P = 0.269\)</span>): EM <span class="math inline">\(= 0.269 \times 0.731 \times 0.25 = 0.049\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>4.9 pp</strong></li>
<li><strong>Persona B</strong> (<span class="math inline">\(P = 0.500\)</span>): EM <span class="math inline">\(= 0.500 \times 0.500 \times 0.25 = 0.063\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>6.3 pp</strong> (máximo)</li>
<li><strong>Persona C</strong> (<span class="math inline">\(P = 0.818\)</span>): EM <span class="math inline">\(= 0.818 \times 0.182 \times 0.25 = 0.037\)</span> <span class="math inline">\(\rightarrow\)</span> <strong>3.7 pp</strong></li>
</ul>
<p>Son exactamente los valores que habíamos calculado antes “a bruto” restando probabilidades. La fórmula simplemente nos da el atajo matemático.</p>
</section>
</section>
<section id="cómo-resumir-el-efecto-en-un-solo-número" class="level3" data-number="3.7.4">
<h3 data-number="3.7.4" class="anchored" data-anchor-id="cómo-resumir-el-efecto-en-un-solo-número"><span class="header-section-number">3.7.4</span> ¿Cómo resumir el efecto en un solo número?</h3>
<p>Ya tenemos claro que el efecto marginal es <strong>distinto para cada individuo</strong>. Pero cuando presentamos resultados necesitamos un solo número que diga “el efecto de la educación es de X puntos porcentuales”. ¿Cómo lo obtenemos?</p>
<p>Hay dos estrategias. Veamos cada una con un ejemplo numérico para que quede claro qué hace cada una.</p>
<section id="opción-1-efecto-marginal-en-la-media-mem" class="level4" data-number="3.7.4.1">
<h4 data-number="3.7.4.1" class="anchored" data-anchor-id="opción-1-efecto-marginal-en-la-media-mem"><span class="header-section-number">3.7.4.1</span> Opción 1: Efecto marginal en la media (MEM)</h4>
<p><strong>¿Qué hace?</strong> Inventa un “individuo promedio” — uno que tenga exactamente la educación media de la muestra, la edad media, etc. — y calcula el efecto marginal solo para él.</p>
<p><span class="math display">\[\text{MEM}_j = f(\bar{x}'\hat{\beta}) \cdot \hat{\beta}_j\]</span></p>
<p><strong>Ejemplo</strong>: si en nuestra muestra la educación media es 13 años, la edad media es 41 años, etc., el MEM toma esa persona ficticia, calcula su <span class="math inline">\(x'\beta\)</span>, obtiene su factor <span class="math inline">\(f\)</span>, y multiplica por <span class="math inline">\(\beta_j\)</span>. Un solo cálculo, un solo número.</p>
<p><strong>¿Cuándo falla?</strong> El “individuo promedio” puede no existir. Por ejemplo, si el sexo medio es 0.48 (48% mujeres), ¿qué es una persona con sexo = 0.48? No tiene sentido. Otro problema: si la distribución de probabilidades en la muestra es muy asimétrica, el individuo medio puede no ser representativo del efecto típico.</p>
<p>En R se obtiene con la opción <code>atmean = TRUE</code>.</p>
</section>
<section id="opción-2-efecto-marginal-promedio-ame-recomendado" class="level4" data-number="3.7.4.2">
<h4 data-number="3.7.4.2" class="anchored" data-anchor-id="opción-2-efecto-marginal-promedio-ame-recomendado"><span class="header-section-number">3.7.4.2</span> Opción 2: Efecto marginal promedio (AME) ★ RECOMENDADO</h4>
<p><strong>¿Qué hace?</strong> En lugar de inventar una persona ficticia, calcula el efecto marginal para <strong>cada una de las N personas reales</strong> de la muestra, y luego toma el promedio:</p>
<p><span class="math display">\[\text{AME}_j = \frac{1}{N} \sum_{i=1}^N \underbrace{f(x_i'\hat{\beta})}_{\text{factor del individuo } i} \cdot \hat{\beta}_j\]</span></p>
<p><strong>Ejemplo con N = 5 personas</strong> (simplificado):</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 30%">
<col style="width: 31%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Individuo</th>
<th style="text-align: center;"><span class="math inline">\(P_i\)</span></th>
<th style="text-align: center;">Factor <span class="math inline">\(f_i = P_i(1-P_i)\)</span></th>
<th style="text-align: center;">EM<span class="math inline">\(_i\)</span> = <span class="math inline">\(f_i \times 0.25\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.30</td>
<td style="text-align: center;">0.210</td>
<td style="text-align: center;">0.053</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.55</td>
<td style="text-align: center;">0.248</td>
<td style="text-align: center;">0.062</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.80</td>
<td style="text-align: center;">0.160</td>
<td style="text-align: center;">0.040</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.45</td>
<td style="text-align: center;">0.248</td>
<td style="text-align: center;">0.062</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5</td>
<td style="text-align: center;">0.70</td>
<td style="text-align: center;">0.210</td>
<td style="text-align: center;">0.053</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[\text{AME} = \frac{0.053 + 0.062 + 0.040 + 0.062 + 0.053}{5} = 0.054 \quad \text{(5.4 pp)}\]</span></p>
<p><strong>¿Por qué es mejor?</strong> Porque usa personas reales, no ficticias. No hay ningún “individuo promedio inventado” — simplemente se promedian los efectos de todos. Es el método <strong>recomendado</strong> en la literatura aplicada.</p>
<p>En R se obtiene con la opción <code>atmean = FALSE</code>.</p>
</section>
<section id="y-para-variables-categóricas-como-sexo" class="level4" data-number="3.7.4.3">
<h4 data-number="3.7.4.3" class="anchored" data-anchor-id="y-para-variables-categóricas-como-sexo"><span class="header-section-number">3.7.4.3</span> ¿Y para variables categóricas (como sexo)?</h4>
<p>La educación es continua: podemos hablar de “un año más” y calcular una derivada. Pero el sexo es una categoría: no podemos hablar de “un poquito más de mujer”, ni tiene sentido calcular una derivada respecto al sexo. Entonces, <strong>¿cómo medimos el efecto de ser mujer?</strong></p>
<p>La idea es sencilla: <strong>simulamos el cambio</strong>. Para cada individuo, calculamos qué probabilidad tendría si fuera hombre y qué probabilidad tendría si fuera mujer, y restamos. Veámoslo paso a paso.</p>
<p><strong>Paso 1 — Tomamos un individuo cualquiera</strong> (por ejemplo, el individuo 1: 14 años de educación, 35 años, 2 hijos, etc.).</p>
<p><strong>Paso 2 — Calculamos su probabilidad “como hombre”</strong>: ponemos sexo = Hombre, dejamos todo lo demás igual, y evaluamos el modelo:</p>
<p><span class="math display">\[P_1^{\text{hombre}} = \Lambda(\hat{\beta}_0 + \hat{\beta}_1 \cdot 14 + \hat{\beta}_2 \cdot 35 + \hat{\beta}_3 \cdot 0 + \cdots) = 0.78\]</span></p>
<p><strong>Paso 3 — Calculamos su probabilidad “como mujer”</strong>: cambiamos <em>solo</em> el sexo a Mujer:</p>
<p><span class="math display">\[P_1^{\text{mujer}} = \Lambda(\hat{\beta}_0 + \hat{\beta}_1 \cdot 14 + \hat{\beta}_2 \cdot 35 + \hat{\beta}_3 \cdot 1 + \cdots) = 0.65\]</span></p>
<p><strong>Paso 4 — Restamos</strong>: el efecto marginal del sexo para este individuo es:</p>
<p><span class="math display">\[\text{EM}_1 = P_1^{\text{mujer}} - P_1^{\text{hombre}} = 0.65 - 0.78 = -0.13 \quad (-13 \text{ pp})\]</span></p>
<p>Es decir, <em>esta persona en concreto</em>, si fuera mujer en lugar de hombre, tendría 13 puntos porcentuales menos de probabilidad de trabajar.</p>
<p><strong>Paso 5 — Repetimos para todos y promediamos (AME)</strong>: hacemos lo mismo para los 500 individuos de la muestra. Cada uno tendrá un efecto diferente (porque sus demás características son distintas). El AME es el promedio:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 27%">
<col style="width: 26%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Individuo</th>
<th style="text-align: center;"><span class="math inline">\(P^{\text{hombre}}\)</span></th>
<th style="text-align: center;"><span class="math inline">\(P^{\text{mujer}}\)</span></th>
<th style="text-align: center;">Efecto del sexo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
<td style="text-align: center;">0.78</td>
<td style="text-align: center;">0.65</td>
<td style="text-align: center;">−13 pp</td>
</tr>
<tr class="even">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0.45</td>
<td style="text-align: center;">0.32</td>
<td style="text-align: center;">−13 pp</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3</td>
<td style="text-align: center;">0.92</td>
<td style="text-align: center;">0.86</td>
<td style="text-align: center;">−6 pp</td>
</tr>
<tr class="even">
<td style="text-align: center;">4</td>
<td style="text-align: center;">0.60</td>
<td style="text-align: center;">0.46</td>
<td style="text-align: center;">−14 pp</td>
</tr>
<tr class="odd">
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
<td style="text-align: center;">…</td>
</tr>
<tr class="even">
<td style="text-align: center;"><strong>AME</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><strong>≈ −12 pp</strong></td>
</tr>
</tbody>
</table>
<p>Fíjate que <strong>el efecto no es igual para todos</strong>: para el individuo 3 (que ya tenía una probabilidad muy alta) el efecto es menor (−6 pp), mientras que para el 4 (en zona intermedia) es mayor (−14 pp). Esto es coherente con todo lo que hemos visto: el efecto es mayor donde hay más incertidumbre.</p>
<blockquote class="blockquote">
<p><strong>En resumen</strong>: para variables categóricas, el efecto marginal es la diferencia de probabilidades “encendiendo y apagando” la categoría, manteniendo todo lo demás constante. El AME promedia esa diferencia para todos los individuos.</p>
</blockquote>
</section>
</section>
<section id="cálculo-en-r-de-los-efectos-marginales" class="level3" data-number="3.7.5">
<h3 data-number="3.7.5" class="anchored" data-anchor-id="cálculo-en-r-de-los-efectos-marginales"><span class="header-section-number">3.7.5</span> Cálculo en R de los efectos marginales</h3>
<p>Todo lo explicado anteriormente se implementa en R. Primero veremos cómo hacerlo “a mano” (para entender qué hace R por dentro) y después con el paquete <code>mfx</code> (lo que usaremos en la práctica).</p>
<section id="cálculo-a-mano" class="level4" data-number="3.7.5.1">
<h4 data-number="3.7.5.1" class="anchored" data-anchor-id="cálculo-a-mano"><span class="header-section-number">3.7.5.1</span> Cálculo “a mano”</h4>
<p>El procedimiento para calcular el efecto marginal de educación en el modelo Logit es:</p>
<ol type="1">
<li>Para <strong>un individuo</strong>: obtener su índice <span class="math inline">\(x'\hat{\beta}\)</span>, calcular su probabilidad <span class="math inline">\(P = \Lambda(x'\hat{\beta})\)</span>, obtener el factor <span class="math inline">\(f = P(1-P)\)</span>, y multiplicar por <span class="math inline">\(\hat{\beta}_{\text{edu}}\)</span>.</li>
<li>Para <strong>el AME</strong>: repetir lo anterior para los N individuos de la muestra y promediar.</li>
</ol>
<p>Internamente, R ejecuta exactamente esos dos pasos — primero para un individuo concreto y luego para todos.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## --- Efecto marginal para UN individuo (el nº 1) ---</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>xb_1   <span class="ot">&lt;-</span> <span class="fu">predict</span>(logit, <span class="at">newdata =</span> datos[<span class="dv">1</span>, ], <span class="at">type =</span> <span class="st">"link"</span>)  <span class="co"># x'b</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>P_1    <span class="ot">&lt;-</span> <span class="fu">plogis</span>(xb_1)                                          <span class="co"># P = L(x'b)</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>f_1    <span class="ot">&lt;-</span> P_1 <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> P_1)                                       <span class="co"># factor de escala</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>me_1   <span class="ot">&lt;-</span> f_1 <span class="sc">*</span> <span class="fu">coef</span>(logit)[<span class="st">"educacion"</span>]                        <span class="co"># EM individual</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"Individuo 1: x'b = %.3f --&gt; P = %.3f --&gt; f = %.3f --&gt; EM = %.4f (%.2f pp)</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>            xb_1, P_1, f_1, me_1, me_1<span class="sc">*</span><span class="dv">100</span>))</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="do">## --- AME: repetimos para TODOS los individuos y promediamos ---</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>xb_todos     <span class="ot">&lt;-</span> <span class="fu">predict</span>(logit, <span class="at">type =</span> <span class="st">"link"</span>)</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>P_todos      <span class="ot">&lt;-</span> <span class="fu">plogis</span>(xb_todos)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>f_todos      <span class="ot">&lt;-</span> P_todos <span class="sc">*</span> (<span class="dv">1</span> <span class="sc">-</span> P_todos)</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>me_edu_todos <span class="ot">&lt;-</span> f_todos <span class="sc">*</span> <span class="fu">coef</span>(logit)[<span class="st">"educacion"</span>]</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"</span><span class="sc">\n</span><span class="st">AME de educación (N = %d individuos):</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">length</span>(me_edu_todos)))</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"  Mínimo:   %.2f pp</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">min</span>(me_edu_todos)<span class="sc">*</span><span class="dv">100</span>))</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"  Máximo:   %.2f pp</span><span class="sc">\n</span><span class="st">"</span>, <span class="fu">max</span>(me_edu_todos)<span class="sc">*</span><span class="dv">100</span>))</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"  PROMEDIO: %.2f pp  &lt;-- este es el AME que reportamos</span><span class="sc">\n</span><span class="st">"</span>,</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mean</span>(me_edu_todos)<span class="sc">*</span><span class="dv">100</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-me-histograma-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Distribución del efecto marginal de educación en la muestra: cada individuo tiene su propio efecto. El AME es el promedio.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="con-el-paquete-mfx-lo-que-haremos-en-la-práctica" class="level4" data-number="3.7.5.2">
<h4 data-number="3.7.5.2" class="anchored" data-anchor-id="con-el-paquete-mfx-lo-que-haremos-en-la-práctica"><span class="header-section-number">3.7.5.2</span> Con el paquete <code>mfx</code> (lo que haremos en la práctica)</h4>
<p>En la práctica no hace falta calcular nada a mano. Todo lo anterior se obtiene automáticamente con una sola línea:</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mfx)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="do">## AME (atmean = FALSE): promedia el efecto de cada individuo</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>logit_mfx <span class="ot">&lt;-</span> <span class="fu">logitmfx</span>(trabaja <span class="sc">~</span> educacion <span class="sc">+</span> edad <span class="sc">+</span> sexo <span class="sc">+</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>                         experiencia <span class="sc">+</span> hijos <span class="sc">+</span> ingreso_familiar,</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> datos, <span class="at">atmean =</span> <span class="cn">FALSE</span>)</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(logit_mfx)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="interpretación-completa-de-los-resultados" class="level4" data-number="3.7.5.3">
<h4 data-number="3.7.5.3" class="anchored" data-anchor-id="interpretación-completa-de-los-resultados"><span class="header-section-number">3.7.5.3</span> Interpretación completa de los resultados</h4>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Efectos marginales promedio (AME) del modelo Logit</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: left;">Cambio unitario</th>
<th style="text-align: right;">AME (pp)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Educación</td>
<td style="text-align: left;">+1 año educ.</td>
<td style="text-align: right;">+2.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">Edad</td>
<td style="text-align: left;">+1 año edad</td>
<td style="text-align: right;">+1.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Experiencia</td>
<td style="text-align: left;">+1 año exp.</td>
<td style="text-align: right;">+0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sexo (Mujer)</td>
<td style="text-align: left;">Mujer vs Hombre</td>
<td style="text-align: right;">-8.85</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hijos</td>
<td style="text-align: left;">+1 hijo menor</td>
<td style="text-align: right;">-4.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ingreso familiar</td>
<td style="text-align: left;">+1.000 EUR ingreso</td>
<td style="text-align: right;">-0.59</td>
</tr>
</tbody>
</table>
</div>
</div>
<blockquote class="blockquote">
<p><strong>Regla para recordar</strong>: en Logit/Probit, <strong>nunca interpretes el coeficiente directamente</strong>. Siempre calcula los efectos marginales. El coeficiente te dice la dirección (+/−); el efecto marginal te dice <strong>cuánto</strong> cambia la probabilidad.</p>
</blockquote>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="odds-ratios-solo-logit" class="level2" data-number="3.8">
<h2 data-number="3.8" class="anchored" data-anchor-id="odds-ratios-solo-logit"><span class="header-section-number">3.8</span> Odds ratios (solo Logit)</h2>
<section id="qué-es-el-odds" class="level3" data-number="3.8.1">
<h3 data-number="3.8.1" class="anchored" data-anchor-id="qué-es-el-odds"><span class="header-section-number">3.8.1</span> ¿Qué es el odds?</h3>
<p>El <strong>odds</strong> es la razón entre la probabilidad de que algo ocurra y la de que no ocurra:</p>
<p><span class="math display">\[\text{Odds} = \frac{P}{1-P}\]</span></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Probabilidad <span class="math inline">\(P\)</span></th>
<th style="text-align: center;">Odds</th>
<th style="text-align: left;">Lectura coloquial</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: left;">“50-50”, equiprobable</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">3.0</td>
<td style="text-align: left;">“3 a 1 a favor”</td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.25</td>
<td style="text-align: center;">0.33</td>
<td style="text-align: left;">“1 a 3 en contra”</td>
</tr>
<tr class="even">
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">9.0</td>
<td style="text-align: left;">“9 a 1 a favor”</td>
</tr>
</tbody>
</table>
</section>
<section id="los-log-odds-y-el-modelo-logit-demostración" class="level3" data-number="3.8.2">
<h3 data-number="3.8.2" class="anchored" data-anchor-id="los-log-odds-y-el-modelo-logit-demostración"><span class="header-section-number">3.8.2</span> Los log-odds y el modelo Logit: demostración</h3>
<p>El modelo Logit tiene una propiedad única que lo distingue del Probit: el índice lineal <span class="math inline">\(x'\beta\)</span> es directamente el <strong>logaritmo del odds</strong> (log-odds). Vamos a demostrarlo paso a paso.</p>
<section id="paso-1-partimos-de-la-función-logística" class="level4" data-number="3.8.2.1">
<h4 data-number="3.8.2.1" class="anchored" data-anchor-id="paso-1-partimos-de-la-función-logística"><span class="header-section-number">3.8.2.1</span> Paso 1: partimos de la función logística</h4>
<p>En el modelo Logit, la probabilidad de éxito es:</p>
<p><span class="math display">\[P = \Lambda(x'\beta) = \frac{1}{1 + e^{-x'\beta}} = \frac{e^{x'\beta}}{1 + e^{x'\beta}}\]</span></p>
</section>
<section id="paso-2-calculamos-1---p" class="level4" data-number="3.8.2.2">
<h4 data-number="3.8.2.2" class="anchored" data-anchor-id="paso-2-calculamos-1---p"><span class="header-section-number">3.8.2.2</span> Paso 2: calculamos <span class="math inline">\(1 - P\)</span></h4>
<p><span class="math display">\[1 - P = 1 - \frac{e^{x'\beta}}{1 + e^{x'\beta}} = \frac{1 + e^{x'\beta} - e^{x'\beta}}{1 + e^{x'\beta}} = \frac{1}{1 + e^{x'\beta}}\]</span></p>
</section>
<section id="paso-3-formamos-el-odds-fracp1-p" class="level4" data-number="3.8.2.3">
<h4 data-number="3.8.2.3" class="anchored" data-anchor-id="paso-3-formamos-el-odds-fracp1-p"><span class="header-section-number">3.8.2.3</span> Paso 3: formamos el odds <span class="math inline">\(\frac{P}{1-P}\)</span></h4>
<p><span class="math display">\[\text{Odds} = \frac{P}{1-P} = \frac{\frac{e^{x'\beta}}{1 + e^{x'\beta}}}{\frac{1}{1 + e^{x'\beta}}} = e^{x'\beta}\]</span></p>
<p>Los <span class="math inline">\((1 + e^{x'\beta})\)</span> se cancelan y queda simplemente <span class="math inline">\(e^{x'\beta}\)</span>.</p>
</section>
<section id="paso-4-tomamos-logaritmo" class="level4" data-number="3.8.2.4">
<h4 data-number="3.8.2.4" class="anchored" data-anchor-id="paso-4-tomamos-logaritmo"><span class="header-section-number">3.8.2.4</span> Paso 4: tomamos logaritmo</h4>
<p><span class="math display">\[\ln\!\left(\frac{P}{1-P}\right) = x'\beta = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots\]</span></p>
<p><strong>Resultado clave</strong>: en el modelo Logit, el logaritmo del odds es una función <strong>lineal</strong> de las variables explicativas. Esto NO ocurre en el Probit.</p>
</section>
<section id="paso-5-demostramos-que-ebeta_j-es-el-odds-ratio" class="level4" data-number="3.8.2.5">
<h4 data-number="3.8.2.5" class="anchored" data-anchor-id="paso-5-demostramos-que-ebeta_j-es-el-odds-ratio"><span class="header-section-number">3.8.2.5</span> Paso 5: demostramos que <span class="math inline">\(e^{\beta_j}\)</span> es el odds ratio</h4>
<p>Queremos ver qué pasa con el odds cuando <span class="math inline">\(x_j\)</span> aumenta en una unidad (de <span class="math inline">\(x_j\)</span> a <span class="math inline">\(x_j + 1\)</span>), manteniendo todo lo demás constante.</p>
<p><strong>Odds cuando</strong> <span class="math inline">\(x_j\)</span> toma su valor original:</p>
<p><span class="math display">\[\text{Odds}_{\text{antes}} = e^{\beta_0 + \cdots + \beta_j \, x_j + \cdots}\]</span></p>
<p><strong>Odds cuando</strong> <span class="math inline">\(x_j\)</span> aumenta en 1 unidad:</p>
<p><span class="math display">\[\text{Odds}_{\text{después}} = e^{\beta_0 + \cdots + \beta_j \, (x_j + 1) + \cdots}\]</span></p>
<p><strong>El odds ratio es el cociente</strong>:</p>
<p><span class="math display">\[OR_j = \frac{\text{Odds}_{\text{después}}}{\text{Odds}_{\text{antes}}} = \frac{e^{\beta_0 + \cdots + \beta_j(x_j+1) + \cdots}}{e^{\beta_0 + \cdots + \beta_j \, x_j + \cdots}}\]</span></p>
<p>Al dividir exponenciales con la misma base, se restan los exponentes. Todos los términos se cancelan excepto el que contiene <span class="math inline">\(\beta_j\)</span>:</p>
<p><span class="math display">\[OR_j = e^{\beta_j(x_j + 1) - \beta_j \, x_j} = e^{\beta_j \, x_j + \beta_j - \beta_j \, x_j} = \boxed{e^{\beta_j}}\]</span></p>
<p><strong>Resultado fundamental</strong>: el odds ratio <span class="math inline">\(e^{\beta_j}\)</span> <strong>no depende del punto de evaluación</strong> <span class="math inline">\(x_j\)</span>. Es constante para cualquier individuo. Esta es la gran ventaja interpretativa del Logit frente al Probit.</p>
</section>
<section id="qué-significa-exactamente-el-odds-ratio-ejemplo-numérico" class="level4" data-number="3.8.2.6">
<h4 data-number="3.8.2.6" class="anchored" data-anchor-id="qué-significa-exactamente-el-odds-ratio-ejemplo-numérico"><span class="header-section-number">3.8.2.6</span> Qué significa exactamente el odds ratio: ejemplo numérico</h4>
<p>Supongamos que estimamos un Logit donde <span class="math inline">\(y\)</span> = “trabaja” (1) o “no trabaja” (0), y una de las variables es <strong>educación</strong> (años). Obtenemos <span class="math inline">\(\hat{\beta}_{\text{edu}} = 0.30\)</span>.</p>
<p>El odds ratio es: <span class="math inline">\(OR = e^{0.30} = 1.350\)</span></p>
<p><strong>Pregunta</strong>: ¿Qué significa exactamente <span class="math inline">\(OR = 1.350\)</span>?</p>
<p>Imaginemos dos personas idénticas en todo (misma edad, sexo, experiencia…) excepto que la Persona B tiene <strong>un año más</strong> de educación que la Persona A.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 36%">
<col style="width: 27%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;"><p>Persona A</p>
<p>(12 años edu.)</p></th>
<th style="text-align: center;"><p>Persona B</p>
<p>(13 años edu.)</p></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Probabilidad de trabajar <span class="math inline">\(P\)</span></td>
<td style="text-align: center;">0.60</td>
<td style="text-align: center;">?</td>
</tr>
<tr class="even">
<td style="text-align: left;">Odds = <span class="math inline">\(P/(1-P)\)</span></td>
<td style="text-align: center;"><span class="math inline">\(0.60/0.40 = 1.50\)</span></td>
<td style="text-align: center;"><span class="math inline">\(1.50 \times 1.350 = 2.025\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Probabilidad resultante</td>
<td style="text-align: center;">0.60</td>
<td style="text-align: center;"><span class="math inline">\(2.025/3.025 = 0.669\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Lectura</strong>: cada año adicional de educación <strong>multiplica</strong> el odds de trabajar por 1.35. Es decir, el odds de la Persona B es un <strong>35% mayor</strong> que el de la Persona A.</p>
</section>
<section id="pero-qué-es-el-odds-exactamente-la-analogía-del-hipódromo" class="level4" data-number="3.8.2.7">
<h4 data-number="3.8.2.7" class="anchored" data-anchor-id="pero-qué-es-el-odds-exactamente-la-analogía-del-hipódromo"><span class="header-section-number">3.8.2.7</span> Pero, ¿qué es el odds exactamente? La analogía del hipódromo</h4>
<p>Es habitual confundir el <strong>odds</strong> con la <strong>probabilidad</strong>. No son lo mismo. Para entenderlo de forma intuitiva, pensemos en un <strong>hipódromo</strong>.</p>
<p>Un caballo tiene un 80% de probabilidades de ganar una carrera.</p>
<ul>
<li><strong>Probabilidad</strong>: 80%. De cada 10 carreras, gana 8.</li>
<li><strong>Odds</strong>: 8 victorias / 2 derrotas = <strong>4 a 1</strong> a favor.</li>
</ul>
<p>El odds nos dice: <strong>“por cada vez que pierde, gana 4 veces”</strong>. Es la ventaja a favor del evento.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 26%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">Probabilidad <span class="math inline">\(P\)</span></th>
<th style="text-align: center;">Odds = <span class="math inline">\(P/(1-P)\)</span></th>
<th style="text-align: left;">Lectura</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.50</td>
<td style="text-align: center;">1.0</td>
<td style="text-align: left;"><p>“50-50”: gana 1 vez</p>
<p>por cada vez que pierde</p></td>
</tr>
<tr class="even">
<td style="text-align: center;">0.75</td>
<td style="text-align: center;">3.0</td>
<td style="text-align: left;"><p>“3 a 1”: gana 3 veces</p>
<p>por cada vez que pierde</p></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0.80</td>
<td style="text-align: center;">4.0</td>
<td style="text-align: left;"><p>“4 a 1”: gana 4 veces</p>
<p>por cada vez que pierde</p></td>
</tr>
<tr class="even">
<td style="text-align: center;">0.90</td>
<td style="text-align: center;">9.0</td>
<td style="text-align: left;"><p>“9 a 1”: gana 9 veces</p>
<p>por cada vez que pierde</p></td>
</tr>
</tbody>
</table>
</section>
<section id="qué-es-entonces-el-odds-ratio-seguimos-en-el-hipódromo" class="level4" data-number="3.8.2.8">
<h4 data-number="3.8.2.8" class="anchored" data-anchor-id="qué-es-entonces-el-odds-ratio-seguimos-en-el-hipódromo"><span class="header-section-number">3.8.2.8</span> ¿Qué es entonces el odds ratio? Seguimos en el hipódromo</h4>
<p>El <strong>odds ratio</strong> responde a la pregunta: <strong>si cambio algo, ¿cuánto se multiplica esa ventaja?</strong></p>
<p><strong>Ejemplo con OR &gt; 1</strong>: le ponemos un <strong>mejor jinete</strong> al caballo. El OR del jinete es 2.0.</p>
<ul>
<li><strong>Antes</strong> (jinete normal): odds = 4 (“gana 4 por cada 1 que pierde”)</li>
<li><strong>Después</strong> (mejor jinete): odds = <span class="math inline">\(4 \times 2.0 = 8\)</span> (“gana 8 por cada 1 que pierde”)</li>
</ul>
<p>El mejor jinete ha <strong>duplicado la ventaja</strong>. Eso es <span class="math inline">\(OR = 2\)</span>.</p>
<p><strong>Ejemplo con OR &lt; 1</strong>: ahora llueve. El OR de la lluvia es 0.50.</p>
<ul>
<li><strong>Antes</strong> (seco): odds = 4 (“gana 4 por cada 1 que pierde”)</li>
<li><strong>Después</strong> (lluvia): odds = <span class="math inline">\(4 \times 0.50 = 2\)</span> (“gana 2 por cada 1 que pierde”)</li>
</ul>
<p>La lluvia ha <strong>reducido la ventaja a la mitad</strong>. Eso es <span class="math inline">\(OR = 0.5\)</span>.</p>
<p><strong>Ejemplo con OR = 1</strong>: le cambiamos la silla de montar. El OR de la silla es 1.0.</p>
<ul>
<li><strong>Antes</strong>: odds = 4. <strong>Después</strong>: odds = <span class="math inline">\(4 \times 1.0 = 4\)</span>. No cambia nada.</li>
</ul>
<p>La silla no afecta. <span class="math inline">\(OR = 1\)</span> significa “sin efecto”.</p>
</section>
<section id="del-hipódromo-a-la-econometría" class="level4" data-number="3.8.2.9">
<h4 data-number="3.8.2.9" class="anchored" data-anchor-id="del-hipódromo-a-la-econometría"><span class="header-section-number">3.8.2.9</span> Del hipódromo a la econometría</h4>
<p>El razonamiento es exactamente el mismo. Si en un Logit de participación laboral obtenemos:</p>
<ul>
<li><strong>Educación</strong>: <span class="math inline">\(OR = 1.35\)</span>. Cada año de educación adicional <strong>mejora la ventaja</strong> de trabajar vs.&nbsp;no trabajar un 35%. Como pasar de “gano 4 a 1” a “gano 5.4 a 1”.</li>
<li><strong>Hijos</strong>: <span class="math inline">\(OR = 0.67\)</span>. Cada hijo <strong>recorta la ventaja</strong> de trabajar un 33%. Como pasar de “gano 4 a 1” a “gano 2.7 a 1”.</li>
</ul>
<p>Volvamos al ejemplo numérico de las Personas A y B:</p>
<ul>
<li>Persona A (12 años edu., <span class="math inline">\(P = 0.60\)</span>): odds = <span class="math inline">\(0.60/0.40 = 1.50\)</span> (“trabaja 1.5 veces por cada vez que no trabaja”)</li>
<li>Persona B (13 años edu.): odds = <span class="math inline">\(1.50 \times 1.35 = 2.025\)</span> (“trabaja 2 veces por cada vez que no trabaja”)</li>
<li>Probabilidad resultante de B: <span class="math inline">\(P = 2.025 / 3.025 = 0.669\)</span></li>
</ul>
</section>
<section id="odds-ratio-neq-cambio-en-probabilidad" class="level4" data-number="3.8.2.10">
<h4 data-number="3.8.2.10" class="anchored" data-anchor-id="odds-ratio-neq-cambio-en-probabilidad"><span class="header-section-number">3.8.2.10</span> Odds ratio <span class="math inline">\(\neq\)</span> cambio en probabilidad</h4>
<p>Atención a un punto que se presta a confusión:</p>
<p><span class="math display">\[\text{El odds subió un 35\%} \quad \neq \quad \text{la probabilidad subió un 35\%}\]</span></p>
<p>La probabilidad pasó de 60.0% a 66.9%: solo subió <strong>~7 puntos porcentuales</strong>. ¿Por qué? Porque odds y probabilidad están relacionados de forma <strong>no lineal</strong>: <span class="math inline">\(P = \text{Odds} / (1 + \text{Odds})\)</span>.</p>
<p>El OR te dice cuánto cambia la <strong>ventaja relativa</strong> (la “apuesta”), no cuánto cambia la probabilidad directamente. Para conocer el cambio en probabilidad, se utilizan los <strong>efectos marginales</strong> (sección 7).</p>
<blockquote class="blockquote">
<p><strong>Regla de oro</strong>: el <strong>OR</strong> comunica cuánto se <em>multiplica la ventaja</em>. Los <strong>efectos marginales</strong> comunican cuánto cambia la <em>probabilidad</em> en puntos porcentuales. Son complementarios.</p>
</blockquote>
<p><strong>Fórmula general para interpretar el cambio porcentual del odds</strong>:</p>
<p><span class="math display">\[\text{Cambio \% en el odds} = (OR - 1) \times 100\]</span></p>
</section>
<section id="guía-de-interpretación-según-el-valor-del-or" class="level4" data-number="3.8.2.11">
<h4 data-number="3.8.2.11" class="anchored" data-anchor-id="guía-de-interpretación-según-el-valor-del-or"><span class="header-section-number">3.8.2.11</span> Guía de interpretación según el valor del OR</h4>
<p><strong>Cuando</strong> <span class="math inline">\(OR &gt; 1\)</span> (el coeficiente <span class="math inline">\(\beta_j\)</span> es positivo):</p>
<ul>
<li><span class="math inline">\(OR = 1.10\)</span>: el odds aumenta un 10% por cada unidad adicional de <span class="math inline">\(x_j\)</span>.</li>
<li><span class="math inline">\(OR = 1.50\)</span>: el odds aumenta un 50%.</li>
<li><span class="math inline">\(OR = 2.00\)</span>: el odds se <strong>duplica</strong>.</li>
<li><span class="math inline">\(OR = 3.00\)</span>: el odds se <strong>triplica</strong>.</li>
</ul>
<p><strong>Cuando</strong> <span class="math inline">\(OR &lt; 1\)</span> (el coeficiente <span class="math inline">\(\beta_j\)</span> es negativo):</p>
<p>Este caso se presta a confusión. Veámoslo con cuidado.</p>
<p>Si <span class="math inline">\(\hat{\beta}_{\text{hijos}} = -0.40\)</span>, entonces <span class="math inline">\(OR = e^{-0.40} = 0.670\)</span>.</p>
<p>Esto significa que cada hijo adicional <strong>multiplica</strong> el odds por <span class="math inline">\(0.670\)</span>. Es decir, el nuevo odds es solo el 67% del anterior: <strong>se reduce un 33%</strong>.</p>
<p>Ejemplo numérico: supongamos que una mujer sin hijos tiene <span class="math inline">\(P = 0.80\)</span> de trabajar:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 38%">
<col style="width: 14%">
<col style="width: 29%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Situación</th>
<th style="text-align: center;">Odds</th>
<th style="text-align: center;">Cálculo</th>
<th style="text-align: center;">P resultante</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sin hijos</td>
<td style="text-align: center;"><span class="math inline">\(0.80/0.20 = 4.00\)</span></td>
<td style="text-align: center;">(partida)</td>
<td style="text-align: center;">0.800</td>
</tr>
<tr class="even">
<td style="text-align: left;">Con 1 hijo</td>
<td style="text-align: center;"><span class="math inline">\(4.00 \times 0.670 = 2.68\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(2.68/3.68 = 0.728\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Con 2 hijos</td>
<td style="text-align: center;"><span class="math inline">\(2.68 \times 0.670 = 1.796\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(1.796/2.796 = 0.642\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Con 3 hijos</td>
<td style="text-align: center;"><span class="math inline">\(1.796 \times 0.670 = 1.203\)</span></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"><span class="math inline">\(1.203/2.203 = 0.546\)</span></td>
</tr>
</tbody>
</table>
<p><strong>Lectura</strong>: cada hijo adicional reduce el odds de trabajar un 33%. Observa que el efecto es <strong>multiplicativo</strong>: no se restan 33 puntos porcentuales, sino que el odds se multiplica por 0.67 cada vez.</p>
<ul>
<li><span class="math inline">\(OR = 0.90\)</span>: el odds se reduce un 10%.</li>
<li><span class="math inline">\(OR = 0.50\)</span>: el odds se reduce un 50% (se divide por 2).</li>
<li><span class="math inline">\(OR = 0.25\)</span>: el odds se reduce un 75% (se divide por 4).</li>
</ul>
<p><strong>Cuando</strong> <span class="math inline">\(OR = 1\)</span> (el coeficiente <span class="math inline">\(\beta_j = 0\)</span>):</p>
<p>La variable no tiene efecto. El odds no cambia. Esto equivale a decir que la variable es irrelevante para predecir <span class="math inline">\(y\)</span>.</p>
<blockquote class="blockquote">
<p><strong>Atención</strong>: el odds ratio mide el cambio en el <strong>odds</strong> (razón <span class="math inline">\(P/(1-P)\)</span>), NO en la probabilidad directamente. Un <span class="math inline">\(OR = 2\)</span> no significa que la probabilidad se duplique. Para conocer el cambio en probabilidad, hay que calcular los efectos marginales (sección 7).</p>
</blockquote>
<blockquote class="blockquote">
<p><strong>Recordatorio</strong>: los odds ratios solo tienen interpretación directa en el modelo <strong>Logit</strong>, porque es el único donde <span class="math inline">\(\ln(\text{Odds}) = x'\beta\)</span> (lineal). En el Probit no se calculan odds ratios — se usan directamente los efectos marginales.</p>
</blockquote>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>OR <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">coef</span>(logit))</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>IC <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fu">confint.default</span>(logit))</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>tabla_or <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">names</span>(OR),</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">OR       =</span> <span class="fu">round</span>(OR, <span class="dv">3</span>),</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC_95_inf =</span> <span class="fu">round</span>(IC[, <span class="dv">1</span>], <span class="dv">3</span>),</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">IC_95_sup =</span> <span class="fu">round</span>(IC[, <span class="dv">2</span>], <span class="dv">3</span>)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(tabla_or, <span class="at">caption =</span> <span class="st">"Odds Ratios del modelo Logit con IC al 95%"</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">row.names =</span> <span class="cn">FALSE</span>, <span class="at">escape =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Odds Ratios del modelo Logit con IC al 95%</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">OR</th>
<th style="text-align: right;">IC_95_inf</th>
<th style="text-align: right;">IC_95_sup</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.036</td>
<td style="text-align: right;">0.009</td>
<td style="text-align: right;">0.137</td>
</tr>
<tr class="even">
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">1.172</td>
<td style="text-align: right;">1.067</td>
<td style="text-align: right;">1.288</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">1.098</td>
<td style="text-align: right;">1.011</td>
<td style="text-align: right;">1.192</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexoMujer</td>
<td style="text-align: right;">0.525</td>
<td style="text-align: right;">0.323</td>
<td style="text-align: right;">0.854</td>
</tr>
<tr class="odd">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">1.001</td>
<td style="text-align: right;">0.923</td>
<td style="text-align: right;">1.085</td>
</tr>
<tr class="even">
<td style="text-align: left;">hijos</td>
<td style="text-align: right;">0.733</td>
<td style="text-align: right;">0.599</td>
<td style="text-align: right;">0.896</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ingreso_familiar</td>
<td style="text-align: right;">0.958</td>
<td style="text-align: right;">0.918</td>
<td style="text-align: right;">0.999</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Ejemplo de interpretación</strong>:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Interpretación de los Odds Ratios del modelo Logit</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">OR</th>
<th style="text-align: right;">Cambio en odds</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">1.172</td>
<td style="text-align: right;">+17.2%</td>
</tr>
<tr class="even">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">1.098</td>
<td style="text-align: right;">+9.8%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sexoMujer</td>
<td style="text-align: right;">0.525</td>
<td style="text-align: right;">-47.5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">1.001</td>
<td style="text-align: right;">+0.1%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hijos</td>
<td style="text-align: right;">0.733</td>
<td style="text-align: right;">-26.7%</td>
</tr>
<tr class="even">
<td style="text-align: left;">ingreso_familiar</td>
<td style="text-align: right;">0.958</td>
<td style="text-align: right;">-4.2%</td>
</tr>
</tbody>
</table>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="bondad-de-ajuste-pseudo-r²-de-mcfadden" class="level2" data-number="3.9">
<h2 data-number="3.9" class="anchored" data-anchor-id="bondad-de-ajuste-pseudo-r²-de-mcfadden"><span class="header-section-number">3.9</span> Bondad de ajuste: Pseudo-R² de McFadden</h2>
<section id="por-qué-no-podemos-usar-el-r²-clásico" class="level3" data-number="3.9.1">
<h3 data-number="3.9.1" class="anchored" data-anchor-id="por-qué-no-podemos-usar-el-r²-clásico"><span class="header-section-number">3.9.1</span> ¿Por qué no podemos usar el R² clásico?</h3>
<p>El <span class="math inline">\(R^2\)</span> clásico del MCO mide la proporción de varianza explicada, pero en modelos binarios estimados por MV no existe una descomposición análoga de la varianza. En su lugar se usa el <strong>Pseudo-R² de McFadden</strong>:</p>
<p><span class="math display">\[\boxed{\tilde{R}^2 = 1 - \frac{\ln L_{SR}}{\ln L_R}}\]</span></p>
<p>donde:</p>
<ul>
<li><span class="math inline">\(\ln L_R\)</span> es la log-verosimilitud del modelo <strong>restringido</strong> (solo la constante, sin variables explicativas).</li>
<li><span class="math inline">\(\ln L_{SR}\)</span> es la log-verosimilitud del modelo <strong>sin restringir</strong> (completo, con todas las variables).</li>
</ul>
<section id="guía-de-interpretación" class="level4" data-number="3.9.1.1">
<h4 data-number="3.9.1.1" class="anchored" data-anchor-id="guía-de-interpretación"><span class="header-section-number">3.9.1.1</span> Guía de interpretación</h4>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Pseudo-R²</th>
<th style="text-align: left;">Interpretación</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(&lt; 0.10\)</span></td>
<td style="text-align: left;">Ajuste débil</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\([0.10, 0.20]\)</span></td>
<td style="text-align: left;">Ajuste aceptable</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\([0.20, 0.40]\)</span></td>
<td style="text-align: left;">Buen ajuste</td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(&gt; 0.40\)</span></td>
<td style="text-align: left;">Ajuste excelente (raro en datos sociales)</td>
</tr>
</tbody>
</table>
<blockquote class="blockquote">
<p><strong>¡Cuidado!</strong> No se puede comparar directamente con el <span class="math inline">\(R^2\)</span> del MCO. Un pseudo-<span class="math inline">\(R^2\)</span> de 0.20 es un resultado perfectamente respetable en microeconometría.</p>
</blockquote>
</section>
</section>
<section id="criterios-de-información-aic-y-bic" class="level3" data-number="3.9.2">
<h3 data-number="3.9.2" class="anchored" data-anchor-id="criterios-de-información-aic-y-bic"><span class="header-section-number">3.9.2</span> Criterios de información: AIC y BIC</h3>
<p>Además del pseudo-<span class="math inline">\(R^2\)</span>, existen dos criterios que permiten comparar modelos de forma más rigurosa: el <strong>Criterio de Información de Akaike (AIC)</strong> y el <strong>Criterio de Información Bayesiano (BIC)</strong>. Ambos parten de la log-verosimilitud pero incorporan una <strong>penalización por complejidad</strong>: cuantos más parámetros tenga el modelo, mayor es la penalización, lo que desincentiva el sobreajuste.</p>
<p>El <strong>AIC</strong> se define como:</p>
<p><span class="math display">\[\text{AIC} = -2 \ln L(\hat{\beta}) + 2k\]</span></p>
<p>donde <span class="math inline">\(\ln L(\hat{\beta})\)</span> es la log-verosimilitud maximizada del modelo y <span class="math inline">\(k\)</span> es el número de parámetros estimados (incluida la constante). El primer término mide la bondad de ajuste (menor $= $ mejor) y el segundo penaliza la complejidad.</p>
<p>El <strong>BIC</strong> (también llamado criterio de Schwarz) incorpora además el tamaño muestral:</p>
<p><span class="math display">\[\text{BIC} = -2 \ln L(\hat{\beta}) + k \ln(n)\]</span></p>
<p>donde <span class="math inline">\(n\)</span> es el número de observaciones. Dado que <span class="math inline">\(\ln(n) &gt; 2\)</span> para cualquier muestra de más de 7 observaciones, el BIC penaliza la complejidad <strong>más severamente</strong> que el AIC y tiende a seleccionar modelos más parsimoniosos.</p>
<p>La interpretación de ambos criterios es sencilla: <strong>menor es mejor</strong>. Al comparar dos modelos estimados sobre los mismos datos, se prefiere el que presente un AIC (o BIC) inferior. Ambos criterios no tienen una escala absoluta — solo tienen sentido como herramienta de comparación relativa entre modelos alternativos.</p>
<p>En la práctica, AIC y BIC no siempre seleccionan el mismo modelo. Cuando discrepan, el AIC suele preferir modelos ligeramente más complejos, mientras que el BIC tiende a ser más conservador. La elección entre uno y otro depende de si se prioriza la capacidad predictiva (AIC) o la parsimonia (BIC).</p>
</section>
<section id="cálculo-en-r" class="level3" data-number="3.9.3">
<h3 data-number="3.9.3" class="anchored" data-anchor-id="cálculo-en-r"><span class="header-section-number">3.9.3</span> Cálculo en R</h3>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Bondad de ajuste: Pseudo-<span class="math inline">\(R^2\)</span> de McFadden, AIC y BIC</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Modelo</th>
<th style="text-align: right;">Pseudo-<span class="math inline">\(R^2\)</span> McFadden</th>
<th style="text-align: right;">AIC</th>
<th style="text-align: right;">BIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Logit</td>
<td style="text-align: right;">0.2403</td>
<td style="text-align: right;">439.5</td>
<td style="text-align: right;">469.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Probit</td>
<td style="text-align: right;">0.2394</td>
<td style="text-align: right;">440.0</td>
<td style="text-align: right;">469.5</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Además, la <strong>tabla de clasificación</strong> proporciona una medida intuitiva de la capacidad predictiva:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Tabla de clasificación (umbral = 0,5). Tasa de aciertos: 81.2%%</caption>
<thead>
<tr class="header">
<th style="text-align: center;">Observado</th>
<th style="text-align: center;">0</th>
<th style="text-align: center;">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">56</td>
<td style="text-align: center;">68</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">26</td>
<td style="text-align: center;">350</td>
</tr>
</tbody>
</table>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="contrastes-de-hipótesis" class="level2" data-number="3.10">
<h2 data-number="3.10" class="anchored" data-anchor-id="contrastes-de-hipótesis"><span class="header-section-number">3.10</span> Contrastes de hipótesis</h2>
<section id="significación-individual-el-test-z-o-test-de-wald-individual" class="level3" data-number="3.10.1">
<h3 data-number="3.10.1" class="anchored" data-anchor-id="significación-individual-el-test-z-o-test-de-wald-individual"><span class="header-section-number">3.10.1</span> Significación individual: el test <span class="math inline">\(z\)</span> (o test de Wald individual)</h3>
<p>Antes de contrastar grupos de variables, la pregunta más básica es: <strong>¿es significativa esta variable concreta?</strong> Es decir, ¿contribuye a explicar <span class="math inline">\(y\)</span>?</p>
<section id="planteamiento-3" class="level4" data-number="3.10.1.1">
<h4 data-number="3.10.1.1" class="anchored" data-anchor-id="planteamiento-3"><span class="header-section-number">3.10.1.1</span> Planteamiento</h4>
<p>Para cada coeficiente <span class="math inline">\(\beta_j\)</span> del modelo, contrastamos:</p>
<p><span class="math display">\[H_0: \beta_j = 0 \qquad \text{(la variable } x_j \text{ NO influye en } y\text{)}\]</span> <span class="math display">\[H_1: \beta_j \neq 0 \qquad \text{(la variable } x_j \text{ SÍ influye en } y\text{)}\]</span></p>
</section>
<section id="el-estadístico" class="level4" data-number="3.10.1.2">
<h4 data-number="3.10.1.2" class="anchored" data-anchor-id="el-estadístico"><span class="header-section-number">3.10.1.2</span> El estadístico</h4>
<p><span class="math display">\[z_j = \frac{\hat{\beta}_j}{\text{SE}(\hat{\beta}_j)} \quad \xrightarrow{d} \quad N(0,1) \qquad \text{bajo } H_0\]</span></p>
<p>donde <span class="math inline">\(\text{SE}(\hat{\beta}_j)\)</span> es el error estándar del coeficiente estimado.</p>
<p><strong>Regla de decisión</strong>: rechazamos <span class="math inline">\(H_0\)</span> (la variable es significativa) si <span class="math inline">\(|z_j| &gt; z_{\alpha/2}\)</span>. Para un nivel del 5%, el valor crítico es <span class="math inline">\(z_{0.025} = 1.96\)</span>.</p>
<p><strong>Equivalentemente</strong>, rechazamos si el <strong>p-valor</strong> <span class="math inline">\(&lt; \alpha\)</span> (habitualmente <span class="math inline">\(\alpha = 0.05\)</span>).</p>
</section>
<section id="dónde-aparece-en-r" class="level4" data-number="3.10.1.3">
<h4 data-number="3.10.1.3" class="anchored" data-anchor-id="dónde-aparece-en-r"><span class="header-section-number">3.10.1.3</span> Dónde aparece en R</h4>
<p>Al hacer <code>summary(modelo)</code>, R muestra una tabla con cuatro columnas para cada coeficiente:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 34%">
<col style="width: 65%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Columna</th>
<th style="text-align: left;">Significado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>Estimate</code></td>
<td style="text-align: left;"><span class="math inline">\(\hat{\beta}_j\)</span> (coeficiente estimado)</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Std. Error</code></td>
<td style="text-align: left;"><span class="math inline">\(\text{SE}(\hat{\beta}_j)\)</span> (error estándar)</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>z value</code></td>
<td style="text-align: left;">El estadístico <span class="math inline">\(z_j = \hat{\beta}_j / \text{SE}(\hat{\beta}_j)\)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>Pr(&gt;|z|)</code></td>
<td style="text-align: left;">El p-valor del contraste bilateral</td>
</tr>
</tbody>
</table>
<p>Los asteriscos al final de cada fila resumen la significación:</p>
<ul>
<li><code>***</code> : p &lt; 0.001 (muy significativo)</li>
<li><code>**</code> : p &lt; 0.01</li>
<li><code>*</code> : p &lt; 0.05</li>
<li><code>.</code> : p &lt; 0.10 (significativo solo al 10%)</li>
<li>(vacío) : no significativo</li>
</ul>
</section>
<section id="tabla-resumen-coeficiente-efecto-marginal-odds-ratio-e-interpretación" class="level4" data-number="3.10.1.4">
<h4 data-number="3.10.1.4" class="anchored" data-anchor-id="tabla-resumen-coeficiente-efecto-marginal-odds-ratio-e-interpretación"><span class="header-section-number">3.10.1.4</span> Tabla resumen: coeficiente, efecto marginal, odds ratio e interpretación</h4>
<p>Para fijar ideas, supongamos un modelo Logit estimado sobre participación laboral (<span class="math inline">\(y\)</span> = trabaja). La tabla siguiente resume los resultados estadísticos:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: center;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: center;">p-valor</th>
<th style="text-align: center;">EM (pp)</th>
<th style="text-align: center;">OR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">educación</td>
<td style="text-align: center;">+0.30</td>
<td style="text-align: center;">&lt;0.001***</td>
<td style="text-align: center;">+5.2</td>
<td style="text-align: center;">1.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexo (Mujer)</td>
<td style="text-align: center;">$-$0.88</td>
<td style="text-align: center;">0.002**</td>
<td style="text-align: center;">$-$15.1</td>
<td style="text-align: center;">0.41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hijos</td>
<td style="text-align: center;">$-$0.40</td>
<td style="text-align: center;">0.013*</td>
<td style="text-align: center;">$-$6.8</td>
<td style="text-align: center;">0.67</td>
</tr>
<tr class="even">
<td style="text-align: left;">experiencia</td>
<td style="text-align: center;">+0.05</td>
<td style="text-align: center;">0.230</td>
<td style="text-align: center;">+0.9</td>
<td style="text-align: center;">1.05</td>
</tr>
</tbody>
</table>
<p><strong>Interpretación de cada variable</strong>:</p>
<p>La <strong>educación</strong> es altamente significativa (<span class="math inline">\(p &lt; 0.001\)</span>). Cada año adicional de educación aumenta la probabilidad de trabajar en 5.2 puntos porcentuales y multiplica el odds por 1.35 (un incremento del 35% en la ventaja relativa).</p>
<p>El <strong>sexo</strong> también es significativo (<span class="math inline">\(p = 0.002\)</span>). Ser mujer, respecto a ser hombre y manteniendo el resto constante, reduce la probabilidad de trabajar en 15.1 puntos porcentuales. El odds de trabajar de una mujer es un 59% inferior al de un hombre con idénticas características (<span class="math inline">\(OR = 0.41\)</span>).</p>
<p>Cada <strong>hijo</strong> adicional reduce la probabilidad en 6.8 puntos porcentuales y el odds en un 33% (<span class="math inline">\(OR = 0.67\)</span>, <span class="math inline">\(p = 0.013\)</span>).</p>
<p>La <strong>experiencia</strong>, en cambio, no resulta significativa (<span class="math inline">\(p = 0.230\)</span>): no se detecta evidencia estadística de que influya en la participación laboral en este modelo.</p>
<blockquote class="blockquote">
<p><strong>Nota</strong>: el coeficiente <span class="math inline">\(\hat{\beta}\)</span> indica la dirección del efecto y permite calcular el OR (exponenciando), pero su magnitud NO es directamente interpretable como cambio en probabilidad. Para eso sirven los efectos marginales.</p>
</blockquote>
</section>
<section id="ejemplo-en-r-1" class="level4" data-number="3.10.1.5">
<h4 data-number="3.10.1.5" class="anchored" data-anchor-id="ejemplo-en-r-1"><span class="header-section-number">3.10.1.5</span> Ejemplo en R</h4>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Test de significación individual (test z) — Modelo Logit</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;"><span class="math inline">\(\hat{\beta}\)</span></th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;"><span class="math inline">\(p\)</span></th>
<th style="text-align: right;">OR</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">0.1586</td>
<td style="text-align: right;">0.0481</td>
<td style="text-align: right;">0.0010</td>
<td style="text-align: right;">1.172</td>
</tr>
<tr class="even">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">0.0932</td>
<td style="text-align: right;">0.0422</td>
<td style="text-align: right;">0.0273</td>
<td style="text-align: right;">1.098</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sexoMujer</td>
<td style="text-align: right;">-0.6437</td>
<td style="text-align: right;">0.2477</td>
<td style="text-align: right;">0.0094</td>
<td style="text-align: right;">0.525</td>
</tr>
<tr class="even">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">0.0012</td>
<td style="text-align: right;">0.0412</td>
<td style="text-align: right;">0.9769</td>
<td style="text-align: right;">1.001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hijos</td>
<td style="text-align: right;">-0.3111</td>
<td style="text-align: right;">0.1024</td>
<td style="text-align: right;">0.0024</td>
<td style="text-align: right;">0.733</td>
</tr>
<tr class="even">
<td style="text-align: left;">ingreso_familiar</td>
<td style="text-align: right;">-0.0434</td>
<td style="text-align: right;">0.0216</td>
<td style="text-align: right;">0.0449</td>
<td style="text-align: right;">0.958</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="test-de-wald-significación-conjunta" class="level3" data-number="3.10.2">
<h3 data-number="3.10.2" class="anchored" data-anchor-id="test-de-wald-significación-conjunta"><span class="header-section-number">3.10.2</span> Test de Wald (significación conjunta)</h3>
<section id="qué-pregunta-responde" class="level4" data-number="3.10.2.1">
<h4 data-number="3.10.2.1" class="anchored" data-anchor-id="qué-pregunta-responde"><span class="header-section-number">3.10.2.1</span> ¿Qué pregunta responde?</h4>
<p>El test <span class="math inline">\(z\)</span> individual que acabamos de ver contrasta si <strong>una sola</strong> variable es significativa. Pero con frecuencia queremos contrastar si <strong>un grupo de variables</strong> es conjuntamente significativo. Por ejemplo: ¿contribuyen conjuntamente las variables demográficas (edad, sexo, hijos) a explicar la participación laboral? Es posible que ninguna de ellas sea individualmente significativa, pero que juntas sí aporten información relevante.</p>
<p>El <strong>test de Wald</strong> responde exactamente a esta pregunta. Su hipótesis nula establece que <strong>todos los coeficientes del grupo</strong> son simultáneamente cero:</p>
<p><span class="math display">\[H_0: \beta_{j_1} = \beta_{j_2} = \cdots = \beta_{j_r} = 0\]</span></p>
<p>Si rechazamos <span class="math inline">\(H_0\)</span>, concluimos que al menos una de las variables del grupo tiene un efecto significativo sobre <span class="math inline">\(y\)</span>.</p>
</section>
<section id="el-estadístico-1" class="level4" data-number="3.10.2.2">
<h4 data-number="3.10.2.2" class="anchored" data-anchor-id="el-estadístico-1"><span class="header-section-number">3.10.2.2</span> El estadístico</h4>
<p>El estadístico de Wald mide la distancia entre los coeficientes estimados y los valores que impone la hipótesis nula (en este caso, cero), ponderada por la precisión de la estimación:</p>
<p><span class="math display">\[W = \hat{d}'\,\hat{V}_d^{-1}\,\hat{d}\]</span></p>
<p>donde <span class="math inline">\(\hat{d} = R\hat{\beta} - q\)</span> es el vector de desviaciones respecto a <span class="math inline">\(H_0\)</span> (si <span class="math inline">\(H_0: \beta = 0\)</span>, entonces <span class="math inline">\(\hat{d} = \hat{\beta}\)</span>) y <span class="math inline">\(\hat{V}_d = R\,\widehat{\text{Var}}(\hat{\beta})\,R'\)</span> es la matriz de varianzas-covarianzas de esas desviaciones.</p>
<p>Bajo <span class="math inline">\(H_0\)</span>, el estadístico sigue asintóticamente una distribución <strong>chi-cuadrado</strong> con <span class="math inline">\(r\)</span> grados de libertad:</p>
<p><span class="math display">\[W \sim \chi^2_r \qquad \text{bajo } H_0\]</span></p>
<p>donde <span class="math inline">\(r\)</span> es el <strong>número de restricciones</strong> que impone la hipótesis nula, es decir, el número de coeficientes que estamos contrastando simultáneamente. Si contrastamos que 3 variables son conjuntamente nulas, <span class="math inline">\(r = 3\)</span> y el estadístico se compara con una <span class="math inline">\(\chi^2_3\)</span>.</p>
</section>
<section id="ejemplo-numérico" class="level4" data-number="3.10.2.3">
<h4 data-number="3.10.2.3" class="anchored" data-anchor-id="ejemplo-numérico"><span class="header-section-number">3.10.2.3</span> Ejemplo numérico</h4>
<p>Supongamos que nuestro modelo Logit de participación laboral tiene 6 variables explicativas (educación, edad, sexo, experiencia, hijos, ingreso familiar) y queremos contrastar si <strong>todas ellas</strong> son conjuntamente significativas. La hipótesis nula es <span class="math inline">\(H_0: \beta_1 = \beta_2 = \cdots = \beta_6 = 0\)</span>, lo que impone <span class="math inline">\(r = 6\)</span> restricciones.</p>
<p>El test calcula <span class="math inline">\(W\)</span> y lo compara con la distribución <span class="math inline">\(\chi^2_6\)</span>. Si <span class="math inline">\(W = 85.3\)</span> y el p-valor asociado es <span class="math inline">\(p &lt; 0.001\)</span>, rechazamos <span class="math inline">\(H_0\)</span>: las variables, en conjunto, sí explican la participación laboral. Un modelo con solo la constante sería significativamente peor.</p>
</section>
<section id="cálculo-en-r-1" class="level4" data-number="3.10.2.4">
<h4 data-number="3.10.2.4" class="anchored" data-anchor-id="cálculo-en-r-1"><span class="header-section-number">3.10.2.4</span> Cálculo en R</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(aod)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="do">## H0: todos los coeficientes (excepto la constante) son cero</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Terms = 2:7 indica que contrastamos los coeficientes 2 a 7 (las 6 variables)</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>wald_logit <span class="ot">&lt;-</span> <span class="fu">wald.test</span>(<span class="at">b =</span> <span class="fu">coef</span>(logit), <span class="at">Sigma =</span> <span class="fu">vcov</span>(logit), <span class="at">Terms =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">7</span>)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(wald_logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="interpretación-del-resultado" class="level4" data-number="3.10.2.5">
<h4 data-number="3.10.2.5" class="anchored" data-anchor-id="interpretación-del-resultado"><span class="header-section-number">3.10.2.5</span> Interpretación del resultado</h4>
<p>El output de <code>wald.test()</code> muestra el valor del estadístico <span class="math inline">\(W\)</span>, los grados de libertad (<span class="math inline">\(r = 6\)</span>, porque contrastamos 6 coeficientes) y el p-valor. Si el p-valor es inferior a 0.05, rechazamos <span class="math inline">\(H_0\)</span> y concluimos que el modelo en su conjunto es significativo: al menos una de las seis variables influye en la probabilidad de trabajar.</p>
<p>Conviene destacar que el test de Wald solo necesita estimar el modelo <strong>completo</strong> (sin restricciones). No requiere estimar el modelo restringido, lo que lo hace computacionalmente eficiente.</p>
</section>
</section>
<section id="test-de-razón-de-verosimilitud-lr" class="level3" data-number="3.10.3">
<h3 data-number="3.10.3" class="anchored" data-anchor-id="test-de-razón-de-verosimilitud-lr"><span class="header-section-number">3.10.3</span> Test de Razón de Verosimilitud (LR)</h3>
<section id="qué-pregunta-responde-1" class="level4" data-number="3.10.3.1">
<h4 data-number="3.10.3.1" class="anchored" data-anchor-id="qué-pregunta-responde-1"><span class="header-section-number">3.10.3.1</span> ¿Qué pregunta responde?</h4>
<p>El test de Razón de Verosimilitud (LR, <em>Likelihood Ratio</em>) responde a la misma pregunta que el test de Wald — ¿es significativo un grupo de variables? — pero utiliza una lógica diferente. En lugar de medir la distancia entre los coeficientes estimados y cero, el test LR <strong>compara directamente cuánto mejora el ajuste</strong> del modelo al incluir las variables en cuestión.</p>
<p>La idea es intuitiva: si añadir las variables mejora sustancialmente la log-verosimilitud, es que aportan información relevante.</p>
</section>
<section id="el-estadístico-2" class="level4" data-number="3.10.3.2">
<h4 data-number="3.10.3.2" class="anchored" data-anchor-id="el-estadístico-2"><span class="header-section-number">3.10.3.2</span> El estadístico</h4>
<p>Se necesitan dos modelos:</p>
<ul>
<li><strong>Modelo restringido</strong> (<span class="math inline">\(M_R\)</span>): el modelo bajo <span class="math inline">\(H_0\)</span>, sin las variables que queremos contrastar. Si la hipótesis es que todas las variables son nulas, el modelo restringido contiene solo la constante.</li>
<li><strong>Modelo sin restringir</strong> (<span class="math inline">\(M_{SR}\)</span>): el modelo completo, con todas las variables.</li>
</ul>
<p>El estadístico LR mide el doble de la diferencia de log-verosimilitudes:</p>
<p><span class="math display">\[LR = 2\left[\ln L(\hat{\beta}_{SR}) - \ln L(\hat{\beta}_{R})\right]\]</span></p>
<p>donde <span class="math inline">\(\ln L(\hat{\beta}_{SR})\)</span> es la log-verosimilitud del modelo completo y <span class="math inline">\(\ln L(\hat{\beta}_{R})\)</span> la del modelo restringido. Dado que el modelo completo siempre ajusta al menos tan bien como el restringido, esta diferencia es siempre <span class="math inline">\(\geq 0\)</span>. Cuanto mayor sea, más evidencia hay contra <span class="math inline">\(H_0\)</span>.</p>
<p>Bajo <span class="math inline">\(H_0\)</span>, el estadístico sigue asintóticamente una distribución chi-cuadrado:</p>
<p><span class="math display">\[LR \sim \chi^2_r \qquad \text{bajo } H_0\]</span></p>
<p>donde <span class="math inline">\(r\)</span> es, de nuevo, el número de restricciones (parámetros que se fijan a cero bajo <span class="math inline">\(H_0\)</span>). Los grados de libertad coinciden con la diferencia en el número de parámetros entre los dos modelos: <span class="math inline">\(r = k_{SR} - k_R\)</span>.</p>
</section>
<section id="ejemplo-numérico-1" class="level4" data-number="3.10.3.3">
<h4 data-number="3.10.3.3" class="anchored" data-anchor-id="ejemplo-numérico-1"><span class="header-section-number">3.10.3.3</span> Ejemplo numérico</h4>
<p>Retomemos nuestro modelo Logit con 6 variables. El modelo completo tiene <span class="math inline">\(k_{SR} = 7\)</span> parámetros (6 coeficientes + la constante) y una log-verosimilitud de, por ejemplo, <span class="math inline">\(\ln L_{SR} = -210.5\)</span>. El modelo restringido (solo la constante) tiene <span class="math inline">\(k_R = 1\)</span> parámetro y <span class="math inline">\(\ln L_R = -253.2\)</span>.</p>
<p>El estadístico LR es:</p>
<p><span class="math display">\[LR = 2 \times [-210.5 - (-253.2)] = 2 \times 42.7 = 85.4\]</span></p>
<p>Los grados de libertad son <span class="math inline">\(r = 7 - 1 = 6\)</span> (las 6 variables que añadimos). El p-valor se obtiene de la distribución <span class="math inline">\(\chi^2_6\)</span>: con <span class="math inline">\(LR = 85.4\)</span>, el p-valor es prácticamente cero (<span class="math inline">\(p &lt; 0.001\)</span>), por lo que rechazamos <span class="math inline">\(H_0\)</span> con total contundencia. Las seis variables, en conjunto, mejoran significativamente el modelo.</p>
</section>
<section id="cálculo-en-r-2" class="level4" data-number="3.10.3.4">
<h4 data-number="3.10.3.4" class="anchored" data-anchor-id="cálculo-en-r-2"><span class="header-section-number">3.10.3.4</span> Cálculo en R</h4>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Modelo restringido: solo la constante (ninguna variable explicativa)</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>logit_nulo <span class="ot">&lt;-</span> <span class="fu">glm</span>(trabaja <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> datos, <span class="at">family =</span> binomial)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Estadistico LR</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>LR_stat <span class="ot">&lt;-</span> <span class="dv">2</span> <span class="sc">*</span> <span class="fu">as.numeric</span>(<span class="fu">logLik</span>(logit) <span class="sc">-</span> <span class="fu">logLik</span>(logit_nulo))</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Grados de libertad: diferencia en numero de parametros</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>LR_df   <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">coef</span>(logit)) <span class="sc">-</span> <span class="fu">length</span>(<span class="fu">coef</span>(logit_nulo))</span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="do">## P-valor de la chi-cuadrado</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>LR_pval <span class="ot">&lt;-</span> <span class="fu">pchisq</span>(LR_stat, <span class="at">df =</span> LR_df, <span class="at">lower.tail =</span> <span class="cn">FALSE</span>)</span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="fu">sprintf</span>(<span class="st">"LR = %.2f,  gl = %d,  p-valor = %.2e</span><span class="sc">\n</span><span class="st">"</span>, LR_stat, LR_df, LR_pval))</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (LR_pval <span class="sc">&lt;</span> <span class="fl">0.05</span>) <span class="fu">cat</span>(<span class="st">"--&gt; Rechazamos H0: el modelo es conjuntamente significativo.</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="wald-vs-lr-cuál-usar" class="level4" data-number="3.10.3.5">
<h4 data-number="3.10.3.5" class="anchored" data-anchor-id="wald-vs-lr-cuál-usar"><span class="header-section-number">3.10.3.5</span> Wald vs LR: ¿cuál usar?</h4>
<p>Ambos tests son <strong>asintóticamente equivalentes</strong>: para muestras grandes producen resultados prácticamente idénticos. Las diferencias son de carácter práctico. El test de Wald solo necesita estimar un modelo (el completo), lo que lo hace más eficiente cuando el modelo restringido es costoso de estimar. El test LR, en cambio, requiere estimar ambos modelos, pero es conceptualmente más directo y, en general, se considera ligeramente más fiable en muestras finitas.</p>
<p>En la práctica, la mayoría de los investigadores reportan ambos, y es habitual que conduzcan a las mismas conclusiones.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="comparación-completa-mlp-vs-probit-vs-logit" class="level2" data-number="3.11">
<h2 data-number="3.11" class="anchored" data-anchor-id="comparación-completa-mlp-vs-probit-vs-logit"><span class="header-section-number">3.11</span> Comparación completa: MLP vs Probit vs Logit</h2>
<section id="coeficientes" class="level3" data-number="3.11.1">
<h3 data-number="3.11.1" class="anchored" data-anchor-id="coeficientes"><span class="header-section-number">3.11.1</span> Coeficientes</h3>
<p>Los coeficientes de los tres modelos <strong>no son directamente comparables</strong> porque están en escalas diferentes. Lo que debe coincidir (y coincide) es:</p>
<ul>
<li>El <strong>signo</strong> de cada coeficiente.</li>
<li>La <strong>significatividad</strong> estadística.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Coeficientes de los tres modelos (escalas NO comparables)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">MLP</th>
<th style="text-align: right;">Probit</th>
<th style="text-align: right;">Logit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.0454</td>
<td style="text-align: right;">-1.9298</td>
<td style="text-align: right;">-3.3250</td>
</tr>
<tr class="even">
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">0.0231</td>
<td style="text-align: right;">0.0924</td>
<td style="text-align: right;">0.1586</td>
</tr>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">0.0127</td>
<td style="text-align: right;">0.0536</td>
<td style="text-align: right;">0.0932</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexoMujer</td>
<td style="text-align: right;">-0.0870</td>
<td style="text-align: right;">-0.3457</td>
<td style="text-align: right;">-0.6437</td>
</tr>
<tr class="odd">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">0.0011</td>
<td style="text-align: right;">0.0000</td>
<td style="text-align: right;">0.0012</td>
</tr>
<tr class="even">
<td style="text-align: left;">hijos</td>
<td style="text-align: right;">-0.0433</td>
<td style="text-align: right;">-0.1837</td>
<td style="text-align: right;">-0.3111</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ingreso_familiar</td>
<td style="text-align: right;">-0.0054</td>
<td style="text-align: right;">-0.0233</td>
<td style="text-align: right;">-0.0434</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="efectos-marginales-sí-son-comparables" class="level3" data-number="3.11.2">
<h3 data-number="3.11.2" class="anchored" data-anchor-id="efectos-marginales-sí-son-comparables"><span class="header-section-number">3.11.2</span> Efectos marginales (sí son comparables)</h3>
<p>Los efectos marginales <strong>sí</strong> se pueden comparar directamente entre los tres modelos:</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Efectos marginales (pp): los tres modelos dan resultados similares</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">MLP_pp</th>
<th style="text-align: right;">Probit_pp</th>
<th style="text-align: right;">Logit_pp</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">educacion</td>
<td style="text-align: right;">2.31</td>
<td style="text-align: right;">2.21</td>
<td style="text-align: right;">2.17</td>
</tr>
<tr class="even">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">1.28</td>
<td style="text-align: right;">1.27</td>
</tr>
<tr class="odd">
<td style="text-align: left;">sexoMujer</td>
<td style="text-align: right;">-8.70</td>
<td style="text-align: right;">-8.30</td>
<td style="text-align: right;">-8.85</td>
</tr>
<tr class="even">
<td style="text-align: left;">experiencia</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hijos</td>
<td style="text-align: right;">-4.33</td>
<td style="text-align: right;">-4.39</td>
<td style="text-align: right;">-4.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">ingreso_familiar</td>
<td style="text-align: right;">-0.54</td>
<td style="text-align: right;">-0.56</td>
<td style="text-align: right;">-0.59</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="gráfico-comparativo" class="level3" data-number="3.11.3">
<h3 data-number="3.11.3" class="anchored" data-anchor-id="gráfico-comparativo"><span class="header-section-number">3.11.3</span> Gráfico comparativo</h3>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="02-eleccion-discreta_files/figure-html/t02-comparacion-grafica-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Los tres modelos ajustados sobre los datos. Probit y Logit son casi idénticos; el MLP puede salir de [0,1].</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="resumen-comparativo" class="level3" data-number="3.11.4">
<h3 data-number="3.11.4" class="anchored" data-anchor-id="resumen-comparativo"><span class="header-section-number">3.11.4</span> Resumen comparativo</h3>
<p><strong>MLP</strong> <span class="math inline">\(\rightarrow\)</span> Simple, rápido, pero con problemas teóricos serios (predicciones fuera de [0,1], heterocedasticidad, efecto marginal constante). Útil como referencia inicial.</p>
<p><strong>Probit</strong> <span class="math inline">\(\rightarrow\)</span> Basado en la distribución Normal estándar. Teóricamente sólido. Interpretación vía efectos marginales. Habitual en economía del trabajo.</p>
<p><strong>Logit</strong> <span class="math inline">\(\rightarrow\)</span> Basado en la distribución logística. Coeficientes interpretables como log-odds. Cálculo más sencillo. El más popular en aplicaciones prácticas.</p>
<p><strong>Conclusión</strong>: Probit y Logit producen resultados <strong>prácticamente idénticos</strong>. La elección depende de la convención del área de investigación y de si interesa interpretar odds ratios (<span class="math inline">\(\rightarrow\)</span> Logit).</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="resumen-lo-esencial-en-10-puntos" class="level2" data-number="3.12">
<h2 data-number="3.12" class="anchored" data-anchor-id="resumen-lo-esencial-en-10-puntos"><span class="header-section-number">3.12</span> Resumen: lo esencial en 10 puntos</h2>
<ol type="1">
<li><p><strong>Variable aleatoria binaria</strong> <span class="math inline">\(y \in \{0, 1\}\)</span> <span class="math inline">\(\rightarrow\)</span> sigue una distribución Bernoulli(<span class="math inline">\(p\)</span>).</p></li>
<li><p><strong>Función de densidad</strong> <span class="math inline">\(f(x)\)</span>: la probabilidad de variables continuas es el <strong>área bajo la curva</strong>.</p></li>
<li><p><strong>CDF</strong> <span class="math inline">\(F(x) = P(X \leq x)\)</span>: siempre en <span class="math inline">\([0, 1]\)</span> <span class="math inline">\(\rightarrow\)</span> perfecta para modelar probabilidades.</p></li>
<li><p><strong>Probit</strong>: <span class="math inline">\(P(y=1) = \Phi(x'\beta)\)</span>. <strong>Logit</strong>: <span class="math inline">\(P(y=1) = \Lambda(x'\beta) = 1/(1+e^{-x'\beta})\)</span>.</p></li>
<li><p><strong>Estimación por MV</strong>: maximizar <span class="math inline">\(\ln L(\beta) = \sum[y_i \ln P_i + (1-y_i)\ln(1-P_i)]\)</span>.</p></li>
<li><p><strong>Coeficientes</strong> <span class="math inline">\(\rightarrow\)</span> solo indican la <em>dirección</em> del efecto (<span class="math inline">\(\beta &gt; 0 \Rightarrow \uparrow P\)</span>); NO son efectos marginales.</p></li>
<li><p><strong>Efectos marginales</strong> <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(\frac{\partial P}{\partial x_j} = f(x'\beta) \cdot \beta_j\)</span>; dependen del punto de evaluación; usar AME.</p></li>
<li><p><strong>Odds Ratios</strong> (solo Logit) <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(OR = e^{\beta}\)</span>; <span class="math inline">\(OR &gt; 1\)</span> aumenta odds, <span class="math inline">\(OR &lt; 1\)</span> reduce odds.</p></li>
<li><p><strong>Pseudo-R² McFadden</strong> <span class="math inline">\(\rightarrow\)</span> <span class="math inline">\(1 - \ln L_{SR}/\ln L_R\)</span>; valores <span class="math inline">\([0.2, 0.4]\)</span> = buen ajuste.</p></li>
<li><p><strong>Contrastes</strong> <span class="math inline">\(\rightarrow\)</span> Wald y LR <span class="math inline">\(\sim \chi^2_r\)</span> bajo <span class="math inline">\(H_0\)</span>; asintóticamente equivalentes.</p></li>
</ol>
<p><strong>Material complementario</strong>: el script <code>T02_mECO_Script_Eleccion.R</code> y la práctica <code>T02_mECO_Practica_CdeA.Rmd</code> (en la carpeta <code>tema2/</code>) contienen la implementación paso a paso de todo lo desarrollado en estos apuntes.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="funciones-esenciales-en-r" class="level2" data-number="3.13">
<h2 data-number="3.13" class="anchored" data-anchor-id="funciones-esenciales-en-r"><span class="header-section-number">3.13</span> Funciones esenciales en R</h2>
<p>A continuación se recogen las funciones de R más relevantes para los modelos de elección discreta tratados en este tema. Su uso detallado se desarrolla en la práctica y el script asociados.</p>
<section id="estimación" class="level3" data-number="3.13.1">
<h3 data-number="3.13.1" class="anchored" data-anchor-id="estimación"><span class="header-section-number">3.13.1</span> Estimación</h3>
<ul>
<li><code>glm(y ~ x1 + x2, family = binomial(link = "probit"), data = datos)</code> — estima un modelo <strong>Probit</strong>.</li>
<li><code>glm(y ~ x1 + x2, family = binomial(link = "logit"), data = datos)</code> — estima un modelo <strong>Logit</strong>.</li>
<li><code>lm(y ~ x1 + x2, data = datos)</code> — estima el <strong>Modelo Lineal de Probabilidad</strong> (MLP) por MCO.</li>
</ul>
</section>
<section id="predicción" class="level3" data-number="3.13.2">
<h3 data-number="3.13.2" class="anchored" data-anchor-id="predicción"><span class="header-section-number">3.13.2</span> Predicción</h3>
<ul>
<li><code>predict(modelo, type = "response")</code> — probabilidades estimadas <span class="math inline">\(\hat{P}(y=1|X)\)</span>.</li>
<li><code>fitted(modelo)</code> — equivalente a <code>predict()</code> con <code>type = "response"</code> para los datos de estimación.</li>
</ul>
</section>
<section id="efectos-marginales-1" class="level3" data-number="3.13.3">
<h3 data-number="3.13.3" class="anchored" data-anchor-id="efectos-marginales-1"><span class="header-section-number">3.13.3</span> Efectos marginales</h3>
<ul>
<li><code>margins::margins(modelo)</code> — calcula los <strong>efectos marginales medios</strong> (AME).</li>
<li><code>margins::margins(modelo, at = list(x1 = valor))</code> — efecto marginal en un punto concreto (MEM).</li>
<li><code>summary(margins(modelo))</code> — tabla con AME, errores estándar e intervalos de confianza.</li>
</ul>
</section>
<section id="odds-ratios-solo-logit-1" class="level3" data-number="3.13.4">
<h3 data-number="3.13.4" class="anchored" data-anchor-id="odds-ratios-solo-logit-1"><span class="header-section-number">3.13.4</span> Odds ratios (solo Logit)</h3>
<ul>
<li><code>exp(coef(modelo))</code> — odds ratios a partir de los coeficientes estimados.</li>
<li><code>exp(confint(modelo))</code> — intervalos de confianza para los odds ratios.</li>
</ul>
</section>
<section id="bondad-de-ajuste" class="level3" data-number="3.13.5">
<h3 data-number="3.13.5" class="anchored" data-anchor-id="bondad-de-ajuste"><span class="header-section-number">3.13.5</span> Bondad de ajuste</h3>
<ul>
<li><code>pscl::pR2(modelo)</code> — pseudo-R² de McFadden y otros.</li>
<li><code>AIC(modelo)</code> / <code>BIC(modelo)</code> — criterios de información.</li>
<li><code>logLik(modelo)</code> — log-verosimilitud del modelo.</li>
</ul>
</section>
<section id="contrastes-de-hipótesis-1" class="level3" data-number="3.13.6">
<h3 data-number="3.13.6" class="anchored" data-anchor-id="contrastes-de-hipótesis-1"><span class="header-section-number">3.13.6</span> Contrastes de hipótesis</h3>
<ul>
<li><code>summary(modelo)</code> — contrastes individuales de Wald (<span class="math inline">\(z\)</span>-test) para cada coeficiente.</li>
<li><code>lmtest::waldtest(modelo_completo, modelo_restringido)</code> — contraste de Wald conjunto.</li>
<li><code>lmtest::coeftest(modelo)</code> — tabla de contrastes con errores estándar robustos si se combinan con <code>sandwich::vcovHC()</code>.</li>
</ul>
</section>
<section id="clasificación" class="level3" data-number="3.13.7">
<h3 data-number="3.13.7" class="anchored" data-anchor-id="clasificación"><span class="header-section-number">3.13.7</span> Clasificación</h3>
<ul>
<li><code>ifelse(predict(modelo, type = "response") &gt; 0.5, 1, 0)</code> — clasificación con umbral 0.5.</li>
<li><code>table(observado, predicho)</code> — matriz de confusión.</li>
<li><code>caret::confusionMatrix(factor(predicho), factor(observado))</code> — métricas completas (accuracy, sensibilidad, especificidad).</li>
</ul>
</section>
<section id="código-r-del-capítulo" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="código-r-del-capítulo">Código R del capítulo</h3>
<p>El script completo de este capítulo (<code>T02_mECO_Script_A01_LOGIT_USA_Help_v2.R</code>) está disponible en el repositorio de material complementario del manual:</p>
<p><a href="https://github.com/carlanta/MicroEconometrics"><strong>https://github.com/carlanta/MicroEconometrics</strong></a></p>
<p>El alumno puede descargar el script directamente desde la carpeta <code>scripts/</code> del repositorio y ejecutarlo en RStudio de forma interactiva.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-page-right">
  <div class="nav-page nav-page-previous">
      <a href="./01-vd-limitada.html" class="pagination-link" aria-label="Datos con Variable Dependiente Limitada">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Datos con Variable Dependiente Limitada</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03-tobit.html" class="pagination-link" aria-label="Modelos para Datos Censurados (Tobit)">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Modelos para Datos Censurados (Tobit)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>